# 将500的中文队名转为transfermkt的英文名

class Chinese_2_english:
    def __init__(self):
        self.team_chinese_2_english_dict = {
        '曼彻斯特城' : 'Manchester City',
        '伯恩利' : 'Burnley FC',
        '伯恩茅斯' : 'AFC Bournemouth',
        '水晶宫' : 'Crystal Palace',
        '西布罗姆维奇' : 'West Bromwich Albion',
        '哈德斯菲尔德' : 'Huddersfield Town',
        '阿森纳' : 'Arsenal FC',
        '利物浦' : 'Liverpool FC',
        '布赖顿' : 'Brighton & Hove Albion',
        '曼彻斯特联' : 'Manchester United',
        '沃特福德' : 'Watford FC',
        '纽卡斯尔联' : 'Newcastle United',
        '切尔西' : 'Chelsea FC',
        '南安普敦' : 'Southampton FC',
        '斯旺西' : 'Swansea City',
        '斯托克城' : 'Stoke City',
        '托特纳姆热刺' : 'Tottenham Hotspur',
        '莱切斯特城' : 'Leicester City',
        '西汉姆联' : 'West Ham United',
        '埃弗顿' : 'Everton FC',
        '狼队' : 'Wolverhampton Wanderers',
        '加的夫城' : 'Cardiff City',
        '富勒姆' : 'Fulham FC',
        '阿斯顿维拉' : 'Aston Villa',
        '米德尔斯堡' : 'Middlesbrough FC',
        '德比郡' : 'Derby County',
        '普雷斯顿' : 'Preston North End',
        '米尔沃尔' : 'Millwall FC',
        '布伦特福德' : 'Brentford FC',
        '谢菲尔德联' : 'Sheffield United',
        '布里斯托尔城' : 'Bristol City',
        '伊普斯维奇' : 'Ipswich Town',
        '利兹联' : 'Leeds United',
        '诺维奇' : 'Norwich City',
        '谢菲尔德星期三' : 'Sheffield Wednesday',
        '女王公园巡游者' : 'Queens Park Rangers',
        '诺丁汉森林' : 'Nottingham Forest',
        '赫尔城' : 'Hull City',
        '伯明翰' : 'Birmingham City',
        '雷丁' : 'Reading FC',
        '博尔顿' : 'Bolton Wanderers',
        '巴恩斯利' : 'Barnsley FC',
        '伯顿' : 'Burton Albion',
        '桑德兰' : 'Sunderland AFC',
        '维冈竞技' : 'Wigan Athletic',
        '布莱克本' : 'Blackburn Rovers',
        '什鲁斯伯里' : 'Shrewsbury Town',
        '罗瑟汉姆' : 'Rotherham United',
        '斯肯索普' : 'Scunthorpe United',
        '查尔顿' : 'Charlton Athletic',
        '普利茅斯' : 'Plymouth Argyle',
        '朴茨茅斯' : 'Portsmouth FC',
        '彼得堡联' : 'Peterborough United',
        '南安联' : 'Southend United',
        '布拉德福德' : 'Bradford City',
        '布莱克浦' : 'Blackpool FC',
        '布里斯托尔流浪' : 'Bristol Rovers',
        '福利特伍德' : 'Fleetwood Town',
        '唐卡斯特' : 'Doncaster Rovers',
        '牛津联' : 'Oxford United',
        '吉灵汉姆' : 'Gillingham FC',
        'AFC温布尔登' : 'AFC Wimbledon',
        '沃尔索尔' : 'Walsall FC',
        '罗奇代尔' : 'Rochdale AFC',
        '奥德汉姆' : 'Oldham Athletic',
        '北安普敦' : 'Northampton Town',
        '米尔顿凯恩斯' : 'Milton Keynes Dons',
        '贝里' : 'Bury FC',
        '阿克宁顿' : 'Accrington Stanley',
        '卢顿' : 'Luton Town',
        '韦康比流浪者' : 'Wycombe Wanderers',
        '埃克赛特城' : 'Exeter City',
        '诺茨郡' : 'Notts County',
        '考文垂' : 'Coventry City',
        '林肯城' : 'Lincoln City',
        '曼斯菲尔德' : 'Mansfield Town',
        '斯文登' : 'Swindon Town',
        '卡利斯尔联' : 'Carlisle United',
        '纽波特郡' : 'Newport County',
        '剑桥联' : 'Cambridge United',
        '科尔切斯特联' : 'Colchester United',
        '克劳利' : 'Crawley Town',
        '克鲁' : 'Crewe Alexandra',
        '斯蒂文尼奇' : 'Stevenage FC',
        '切尔滕汉姆' : 'Cheltenham Town',
        '格林斯比' : 'Grimsby Town',
        '约维尔' : 'Yeovil Town',
        '维尔港' : 'Port Vale FC',
        '格兰森林流浪' : 'Forest Green Rovers',
        '莫克姆' : 'Morecambe FC',
        '巴尼特' : 'Barnet FC',
        '切斯特菲尔德' : 'Chesterfield FC',
        '麦克尔斯菲尔德' : 'Macclesfield Town',
        '赫雷福德联' : 'FC Hereford',
        '奥尔德肖特' : 'Aldershot Town',
        '巴塞罗那' : 'FC Barcelona',
        '马德里竞技' : 'Atlético Madrid',
        '皇家贝蒂斯' : 'Real Betis Balompié',
        '皇家马德里' : 'Real Madrid',
        '巴伦西亚' : 'Valencia CF',
        '赫塔费' : 'Getafe CF',
        '埃瓦尔' : 'SD Eibar',
        '塞维利亚' : 'Sevilla FC',
        '西班牙人' : 'RCD Espanyol Barcelona',
        '阿拉维斯' : 'Deportivo Alavés',
        '维戈塞尔塔' : 'Celta de Vigo',
        '莱加内斯' : 'CD Leganés',
        '毕尔巴鄂竞技' : 'Athletic Bilbao',
        '莱万特' : 'Levante UD',
        '皇家社会' : 'Real Sociedad',
        '比利亚雷亚尔' : 'Villarreal CF',
        '赫罗纳' : 'Girona FC',
        '拉科鲁尼亚' : 'Deportivo de La Coruña',
        '拉斯帕尔马斯' : 'UD Las Palmas',
        '马拉加' : 'Málaga CF',
        '巴列卡诺' : 'Rayo Vallecano',
        '韦斯卡' : 'SD Huesca',
        '希洪竞技' : 'Sporting Gijón',
        '萨拉戈萨' : 'Real Zaragoza',
        '巴利亚多利德' : 'Real Valladolid CF',
        '努曼西亚' : 'CD Numancia',
        '皇家奥维耶多' : 'Real Oviedo',
        '加的斯' : 'Cádiz CF',
        '奥萨苏纳' : 'CA Osasuna',
        '格拉纳达CF' : 'Granada CF',
        '特内里费' : 'CD Tenerife',
        '鲁勾' : 'CD Lugo',
        '阿尔科尔孔' : 'AD Alcorcón',
        '塔拉戈纳' : 'Gimnàstic de Tarragona',
        '雷乌斯' : 'CF Reus Deportiu',
        '科尔多瓦' : 'Córdoba CF',
        '阿尔瓦塞特' : 'Albacete Balompié',
        '阿尔梅里亚' : 'UD Almería',
        '莱昂内萨' : 'Cultural Leonesa',
        '巴塞罗那B队' : 'FC Barcelona B',
        '合亚' : 'Lorca FC',
        '塞维利亚B队' : 'Sevilla Atlético',
        '埃尔切' : 'Elche CF',
        '瑞欧马加达宏达' : 'CF Rayo Majadahonda',
        '马洛卡' : 'RCD Mallorca',
        '巴黎圣日尔曼' : 'Paris Saint-Germain',
        '摩纳哥' : 'AS Monaco',
        '里昂' : 'Olympique Lyon',
        '马赛' : 'Olympique Marseille',
        '雷恩' : 'Stade Rennais FC',
        '波尔多' : 'FC Girondins Bordeaux',
        '圣埃蒂安' : 'AS Saint-Étienne',
        '尼斯' : 'OGC Nice',
        '南特' : 'FC Nantes',
        '蒙彼利埃' : 'HSC Montpellier',
        '第戎' : 'FCO Dijon',
        '甘冈' : 'EA Guingamp',
        '亚眠' : 'SC Amiens',
        '昂热' : 'SCO Angers',
        '斯特拉斯堡' : 'RC Strasbourg Alsace',
        '卡昂' : 'SM Caen',
        '里尔' : 'LOSC Lille',
        '图卢兹' : 'FC Toulouse',
        '特鲁瓦' : 'ES Troyes AC',
        '梅斯' : 'FC Metz',
        '兰斯' : 'Stade Reims',
        '尼姆' : 'Nîmes Olympique',
        '瓦朗谢纳' : 'Valenciennes FC',
        '贝兹尔' : 'AS Béziers',
        '朗斯' : 'RC Lens',
        '尼奥尔' : 'FC Chamois Niort',
        '格勒诺布尔' : 'Grenoble Foot 38',
        '阿雅克肖GFCO' : 'GFC Ajaccio',
        '巴黎FC' : 'Paris FC',
        '克莱蒙' : 'Clermont Foot Auvergne 63',
        '洛里昂' : 'FC Lorient',
        '勒阿弗尔' : 'AC Le Havre',
        '沙托鲁' : 'LB Châteauroux',
        '圣旺红星' : 'Red Star FC',
        '索肖' : 'FC Sochaux-Montbéliard',
        '布雷斯特' : 'Stade Brest 29',
        '阿雅克肖' : 'AC Ajaccio',
        '欧塞尔' : 'AJ Auxerre',
        '南锡' : 'AS Nancy-Lorraine',
        '奥尔良' : 'US Orléans',
        '布尔格' : 'Bourg-en-Bresse Péronnas 01',
        '奎维利鲁昂' : 'US Quevilly',
        '图尔' : 'Tours FC',
    }

    def get(self, name):
        return self.team_chinese_2_english_dict[name]

