# 将500的中文队名转为transfermkt的英文名

class Chinese_2_english:
    def __init__(self):
        self.team_chinese_2_english_dict = {
        '曼彻斯特城' : 'Manchester City',
        '曼城' : 'Manchester City',
        '伯恩利' : 'Burnley FC',
        '伯恩茅斯' : 'AFC Bournemouth',
        'AFC伯恩' : 'AFC Bournemouth',
        '水晶宫' : 'Crystal Palace',
        '西布罗姆维奇' : 'West Bromwich Albion',
        '西布罗姆维' : 'West Bromwich Albion',
        '西布罗' : 'West Bromwich Albion',
        '哈德斯菲尔德' : 'Huddersfield Town',
        '哈德斯菲尔' : 'Huddersfield Town',
        '阿森纳' : 'Arsenal FC',
        '利物浦' : 'Liverpool FC',
        '布赖顿' : 'Brighton & Hove Albion',
        '布莱顿' : 'Brighton & Hove Albion',
        '曼彻斯特联' : 'Manchester United',
        '曼联' : 'Manchester United',
        '沃特福德' : 'Watford FC',
        '纽卡斯尔联' : 'Newcastle United',
        '切尔西' : 'Chelsea FC',
        '南安普敦' : 'Southampton FC',
        '斯旺西' : 'Swansea City',
        '斯托克城' : 'Stoke City',
        '托特纳姆热刺' : 'Tottenham Hotspur',
        '托特纳姆热' : 'Tottenham Hotspur',
        '莱切斯特城' : 'Leicester City',
        '西汉姆联' : 'West Ham United',
        '西汉姆联队' : 'West Ham United',
        '埃弗顿' : 'Everton FC',
        '狼队' : 'Wolverhampton Wanderers',
        '加的夫城' : 'Cardiff City',
        '卡迪夫城' : 'Cardiff City',
        '南安普顿' : 'Southampton FC',
        '富勒姆' : 'Fulham FC',
        '阿斯顿维拉' : 'Aston Villa',
        '维拉' : 'Aston Villa',
        '米德尔斯堡' : 'Middlesbrough FC',
        '德比郡' : 'Derby County',
        '普雷斯顿' : 'Preston North End',
        '米尔沃尔' : 'Millwall FC',
        '布伦特福德' : 'Brentford FC',
        '谢菲尔德联' : 'Sheffield United',
        '谢菲联' : 'Sheffield United',
        '布里斯托尔城' : 'Bristol City',
        '布里斯城' : 'Bristol City',
        '伊普斯维奇' : 'Ipswich Town',
        '利兹联' : 'Leeds United',
        '诺维奇' : 'Norwich City',
        '谢菲尔德星期三' : 'Sheffield Wednesday',
        '谢周三' : 'Sheffield Wednesday',
        '女王公园巡游者' : 'Queens Park Rangers',
        '女王公园巡' : 'Queens Park Rangers',
        '诺丁汉森林' : 'Nottingham Forest',
        '诺丁汉' : 'Nottingham Forest',
        '赫尔城' : 'Hull City',
        '伯明翰' : 'Birmingham City',
        '雷丁' : 'Reading FC',
        '博尔顿' : 'Bolton Wanderers',
        '巴恩斯利' : 'Barnsley FC',
        '伯顿' : 'Burton Albion',
        '桑德兰' : 'Sunderland AFC',
        '维冈竞技' : 'Wigan Athletic',
        '布莱克本' : 'Blackburn Rovers',
        '什鲁斯伯里' : 'Shrewsbury Town',
        '罗瑟汉姆' : 'Rotherham United',
        '斯肯索普' : 'Scunthorpe United',
        '查尔顿' : 'Charlton Athletic',
        '普利茅斯' : 'Plymouth Argyle',
        '朴茨茅斯' : 'Portsmouth FC',
        '彼得堡联' : 'Peterborough United',
        '皮特堡联' : 'Peterborough United',
        '南安联' : 'Southend United',
        '布拉德福德' : 'Bradford City',
        '布莱克浦' : 'Blackpool FC',
        '布里斯托尔流浪' : 'Bristol Rovers',
        '布里流浪' : 'Bristol Rovers',
        '福利特伍德' : 'Fleetwood Town',
        '弗利特伍德' : 'Fleetwood Town',
        '唐卡斯特' : 'Doncaster Rovers',
        '牛津联' : 'Oxford United',
        '牛津联队' : 'Oxford United',
        '吉灵汉姆' : 'Gillingham FC',
        '吉林汉姆' : 'Gillingham FC',
        'AFC温布尔登' : 'AFC Wimbledon',
        'AFC温布' : 'AFC Wimbledon',
        '沃尔索尔' : 'Walsall FC',
        '罗奇代尔' : 'Rochdale AFC',
        '奥德汉姆' : 'Oldham Athletic',
        '北安普敦' : 'Northampton Town',
        '北安普顿' : 'Northampton Town',
        '米尔顿凯恩斯' : 'Milton Keynes Dons',
        '米尔顿凯恩' : 'Milton Keynes Dons',
        '贝里' : 'Bury FC',
        '伯利' : 'Bury FC',
        '阿克宁顿' : 'Accrington Stanley',
        '阿克灵顿' : 'Accrington Stanley',
        '卢顿' : 'Luton Town',
        '韦康比流浪者' : 'Wycombe Wanderers',
        '威科姆流浪' : 'Wycombe Wanderers',
        '埃克赛特城' : 'Exeter City',
        '埃克塞特城' : 'Exeter City',
        '诺茨郡' : 'Notts County',
        '考文垂' : 'Coventry City',
        '林肯城' : 'Lincoln City',
        '曼斯菲尔德' : 'Mansfield Town',
        '斯文登' : 'Swindon Town',
        '卡利斯尔联' : 'Carlisle United',
        '纽波特郡' : 'Newport County',
        '纽波特' : 'Newport County',
        '剑桥联' : 'Cambridge United',
        '科尔切斯特联' : 'Colchester United',
        '科切斯特联' : 'Colchester United',
        '克劳利' : 'Crawley Town',
        '克鲁' : 'Crewe Alexandra',
        '斯蒂文尼奇' : 'Stevenage FC',
        '斯蒂夫尼奇' : 'Stevenage FC',
        '切尔滕汉姆' : 'Cheltenham Town',
        '格林斯比' : 'Grimsby Town',
        '格里姆斯比' : 'Grimsby Town',
        '约维尔' : 'Yeovil Town',
        '耶奥维尔' : 'Yeovil Town',
        '维尔港' : 'Port Vale FC',
        '格兰森林流浪' : 'Forest Green Rovers',
        '绿森林流浪' : 'Forest Green Rovers',
        '莫克姆' : 'Morecambe FC',
        '巴尼特' : 'Barnet FC',
        '切斯特菲尔德' : 'Chesterfield FC',
        '麦克尔斯菲尔德' : 'Macclesfield Town',
        '麦克尔斯菲' : 'Macclesfield Town',
        '赫雷福德联' : 'FC Hereford',
        '奥尔德肖特' : 'Aldershot Town',
        '莱顿东方' : 'Leyton Orient',
        '特兰米尔' : 'Tranmere Rovers',
        '哈特利普' : 'Hartlepool United',
        '达根汉姆' : 'Dagenham & Redbridge FC',
        '约克城' : 'York City',
        '托基联' : 'Torquay United FC',
        '斯托克港' : 'Stockport County',
        '巴塞罗那' : 'FC Barcelona',
        '马德里竞技' : 'Atlético Madrid',
        '皇家贝蒂斯' : 'Real Betis Balompié',
        '皇家马德里' : 'Real Madrid',
        '皇马' : 'Real Madrid',
        '巴伦西亚' : 'Valencia CF',
        '赫塔费' : 'Getafe CF',
        '埃瓦尔' : 'SD Eibar',
        '塞维利亚' : 'Sevilla FC',
        '西班牙人' : 'RCD Espanyol Barcelona',
        '阿拉维斯' : 'Deportivo Alavés',
        '维戈塞尔塔' : 'Celta de Vigo',
        '莱加内斯' : 'CD Leganés',
        '毕尔巴鄂竞技' : 'Athletic Bilbao',
        '莱万特' : 'Levante UD',
        '皇家社会' : 'Real Sociedad',
        '比利亚雷亚尔' : 'Villarreal CF',
        '赫罗纳' : 'Girona FC',
        '拉科鲁尼亚' : 'Deportivo de La Coruña',
        '拉斯帕尔马斯' : 'UD Las Palmas',
        '马拉加' : 'Málaga CF',
        '巴列卡诺' : 'Rayo Vallecano',
        '韦斯卡' : 'SD Huesca',
        '希洪竞技' : 'Sporting Gijón',
        '萨拉戈萨' : 'Real Zaragoza',
        '巴利亚多利德' : 'Real Valladolid CF',
        '努曼西亚' : 'CD Numancia',
        '皇家奥维耶多' : 'Real Oviedo',
        '加的斯' : 'Cádiz CF',
        '奥萨苏纳' : 'CA Osasuna',
        '格拉纳达CF' : 'Granada CF',
        '特内里费' : 'CD Tenerife',
        '鲁勾' : 'CD Lugo',
        '阿尔科尔孔' : 'AD Alcorcón',
        '塔拉戈纳' : 'Gimnàstic de Tarragona',
        '雷乌斯' : 'CF Reus Deportiu',
        '科尔多瓦' : 'Córdoba CF',
        '阿尔瓦塞特' : 'Albacete Balompié',
        '阿尔梅里亚' : 'UD Almería',
        '莱昂内萨' : 'Cultural Leonesa',
        '巴塞罗那B队' : 'FC Barcelona B',
        '合亚' : 'Lorca FC',
        '塞维利亚B队' : 'Sevilla Atlético',
        '埃尔切' : 'Elche CF',
        '瑞欧马加达宏达' : 'CF Rayo Majadahonda',
        '马洛卡' : 'RCD Mallorca',
        '穆尔西亚天主大学' : 'UCAM Murcia CF',
        '米兰德斯' : 'CD Mirandés',
        '桑坦德竞技' : 'Racing Santander',
        '毕尔巴鄂B队' : 'Bilbao Athletic',
        '埃尔库莱斯' : 'Hércules CF',
        '邦费雷迪纳' : 'SD Ponferradina',
        '利亚格斯特拉' : 'UE Llagostera',
        '韦尔瓦' : 'Recreativo Huelva',
        '萨瓦德尔' : 'CE Sabadell',
        '穆尔西亚' : 'UCAM Murcia CF',
        '皇家马德里B队' : 'Real Madrid Castilla',
        '皇家哈恩' : 'Real Jaén CF',
        'CD瓜达拉哈拉' : 'CD Guadalajara',
        '萨雷斯' : 'Xerez Deportivo FC',
        '卡塔赫纳' : 'FC Cartagena',
        '维拉利尔B队' : 'Villarreal CF B',
        '阿尔科亚诺' : 'CD Alcoyano',
        '萨拉曼卡' : 'Salamanca CF UDS',
        '巴黎圣日尔曼' : 'Paris Saint-Germain',
        '巴黎圣日尔' : 'Paris Saint-Germain',
        '摩纳哥' : 'AS Monaco',
        '里昂' : 'Olympique Lyon',
        '马赛' : 'Olympique Marseille',
        '雷恩' : 'Stade Rennais FC',
        '波尔多' : 'FC Girondins Bordeaux',
        '圣埃蒂安' : 'AS Saint-Étienne',
        '尼斯' : 'OGC Nice',
        '南特' : 'FC Nantes',
        '蒙彼利埃' : 'HSC Montpellier',
        '第戎' : 'FCO Dijon',
        '甘冈' : 'EA Guingamp',
        '亚眠' : 'SC Amiens',
        '昂热' : 'SCO Angers',
        '安格斯' : 'SCO Angers',
        '斯特拉斯堡' : 'RC Strasbourg Alsace',
        '卡昂' : 'SM Caen',
        '里尔' : 'LOSC Lille',
        '图卢兹' : 'FC Toulouse',
        '特鲁瓦' : 'ES Troyes AC',
        '梅斯' : 'FC Metz',
        '兰斯' : 'Stade Reims',
        '尼姆' : 'Nîmes Olympique',
        '瓦朗谢纳' : 'Valenciennes FC',
        '贝兹尔' : 'AS Béziers',
        '贝济耶' : 'AS Béziers',
        '朗斯' : 'RC Lens',
        '尼奥尔' : 'FC Chamois Niort',
        '尼奥特' : 'FC Chamois Niort',
        '格勒诺布尔' : 'Grenoble Foot 38',
        '阿雅克肖GFCO' : 'GFC Ajaccio',
        'GFC阿雅' : 'GFC Ajaccio',
        '巴黎FC' : 'Paris FC',
        '克莱蒙' : 'Clermont Foot Auvergne 63',
        '克莱蒙特' : 'Clermont Foot Auvergne 63',
        '洛里昂' : 'FC Lorient',
        '勒阿弗尔' : 'AC Le Havre',
        '沙托鲁' : 'LB Châteauroux',
        '圣旺红星' : 'Red Star FC',
        '索肖' : 'FC Sochaux-Montbéliard',
        '布雷斯特' : 'Stade Brest 29',
        '阿雅克肖' : 'AC Ajaccio',
        '欧塞尔' : 'AJ Auxerre',
        '南锡' : 'AS Nancy-Lorraine',
        '奥尔良' : 'US Orléans',
        '布尔格' : 'Bourg-en-Bresse Péronnas 01',
        '奎维利鲁昂' : 'US Quevilly',
        '图尔' : 'Tours FC',
        '巴斯蒂亚' : 'SC Bastia',
        '伊维恩' : 'FC Évian Thonon Gaillard',
        '拉瓦勒' : 'Stade Laval',
        '克雷泰伊' : 'US Créteil-Lusitanos',
        '阿尔勒' : 'Athlétic Club Arlésien',
        '伊斯特尔' : 'Istres Football Club',
        'CA巴斯蒂亚' : 'CA Bastia',
        '色当' : 'CS Sedan-Ardennes',
        '勒芒' : 'FC Le Mans',
        '布洛涅' : 'US Boulogne',
        '瓦讷' : 'OC Vannes',
        '拜仁慕尼黑' : 'Bayern Munich',
        '沙尔克04' : 'FC Schalke 04',
        '霍芬海姆' : 'TSG 1899 Hoffenheim',
        '多特蒙德' : 'Borussia Dortmund',
        '勒沃库森' : 'Bayer 04 Leverkusen',
        '莱比锡红牛' : 'RB Leipzig',
        '斯图加特' : 'VfB Stuttgart',
        '法兰克福' : 'Eintracht Frankfurt',
        '门兴格拉德巴赫' : 'Borussia Mönchengladbach',
        '柏林赫塔' : 'Hertha BSC',
        '云达不来梅' : 'SV Werder Bremen',
        '奥格斯堡' : 'FC Augsburg',
        '汉诺威96' : 'Hannover 96',
        '美因茨' : '1.FSV Mainz 05',
        '弗赖堡' : 'SC Freiburg',
        '沃尔夫斯堡' : 'VfL Wolfsburg',
        '汉堡' : 'Hamburger SV',
        '科隆' : '1. FC Köln',
        '杜塞尔多夫' : 'Fortuna Düsseldorf',
        '纽伦堡' : '1.FC Nuremberg',
        '基尔高士丁' : 'Holstein Kiel',
        '基尔' : 'Holstein Kiel',
        '比勒费尔德' : 'Arminia Bielefeld',
        '雷根斯堡' : 'SSV Jahn Regensburg',
        '波鸿' : 'VfL Bochum',
        '杜伊斯堡' : 'MSV Duisburg',
        '柏林联合' : '1.FC Union Berlin',
        '因戈尔施塔特' : 'FC Ingolstadt 04',
        '英戈尔施塔' : 'FC Ingolstadt 04',
        '达姆施塔特' : 'SV Darmstadt 98',
        '桑德豪森' : 'SV Sandhausen',
        '圣保利' : 'FC St. Pauli',
        '海登海姆' : '1.FC Heidenheim 1846',
        '德累斯顿' : 'SG Dynamo Dresden',
        '菲尔特' : 'SpVgg Greuther Fürth',
        '奥厄' : 'FC Erzgebirge Aue',
        '不伦瑞克' : 'Eintracht Braunschweig',
        '凯泽斯劳滕' : '1.FC Kaiserslautern',
        '帕德博恩' : 'SC Paderborn 07',
        '马迪堡' : '1.FC Magdeburg',
        '马格德堡' : '1.FC Magdeburg',
        '卡尔斯鲁厄' : 'Karlsruher SC',
        '慕尼黑1860' : 'TSV 1860 Munich',
        '维尔茨堡踢球者' : 'Würzburger Kickers',
        'FSV法兰克福' : 'FSV Frankfurt',
        '亚伦' : 'VfR Aalen',
        '科特布斯' : 'FC Energie Cottbus',
        '罗斯托克' : 'FC Hansa Rostock',
        '亚琛' : 'Alemannia Aachen',
        '奥伯豪森' : 'Rot-Weiß Oberhausen',
        '奥斯纳布吕克' : 'VfL Osnabrück',
        '尤文图斯' : 'Juventus FC',
        '那不勒斯' : 'SSC Napoli',
        '罗马' : 'AS Roma',
        '国际米兰' : 'Inter Milan',
        '拉齐奥' : 'SS Lazio',
        'AC米兰' : 'AC Milan',
        '亚特兰大' : 'Atalanta BC',
        '佛罗伦萨' : 'ACF Fiorentina',
        '都灵' : 'Torino FC',
        '桑普多利亚' : 'UC Sampdoria',
        '萨索洛' : 'US Sassuolo',
        '热那亚' : 'Genoa CFC',
        '乌迪内斯' : 'Udinese Calcio',
        '切沃' : 'Chievo Verona',
        '博洛尼亚' : 'Bologna FC 1909',
        '卡利亚里' : 'Cagliari Calcio',
        '费拉拉SPAL' : 'SPAL 2013',
        '克罗托内' : 'FC Crotone',
        '维罗纳' : 'Hellas Verona',
        '贝内文托' : 'Benevento Calcio',
        '恩波利' : 'FC Empoli',
        '帕尔马' : 'Parma Calcio 1913',
        '弗洛西诺内' : 'Frosinone Calcio',
        '巴勒莫' : 'US Palermo',
        '威尼斯' : 'Venezia FC',
        '巴里' : 'FC Bari 1908',
        '希塔德拉' : 'AS Cittadella',
        '佩鲁贾' : 'AC Perugia Calcio',
        '霍治亚' : 'Foggia Calcio',
        '斯佩齐亚' : 'Spezia Calcio',
        '卡尔皮' : 'Carpi FC 1909',
        '萨勒尼塔纳' : 'US Salernitana 1919',
        '切塞纳' : 'Romagna Centro Cesena FC',
        '科雷蒙尼斯' : 'US Cremonese',
        '阿韦利诺' : 'AS Livorno',
        '布雷西亚' : 'Brescia Calcio',
        '佩斯卡拉' : 'Delfino Pescara 1936',
        '阿斯科利' : 'Ascoli Calcio',
        '诺瓦拉' : 'Novara Calcio 1908',
        '恩特拉' : 'Virtus Entella',
        '韦尔切利' : 'FC Pro Vercelli 1892',
        '特拉纳' : 'Ternana Calcio',
        '莱切' : 'US Lecce',
        '帕多瓦' : 'Calcio Padova',
        '比萨' : 'AC Pisa 1909',
        '拉蒂那' : 'Latina Calcio 1932',
        '维琴察' : 'LR Vicenza 1902',
        '特腊帕尼' : 'Trapani Calcio',
        '利沃诺' : 'AS Livorno',
        '兰恰诺' : 'SS Virtus Lanciano',
        '摩德纳' : 'Modena FC 2018',
        '科莫' : 'Como 1907',
        '卡塔尼亚' : 'Calcio Catania',
        '瓦雷泽' : 'Varese Calcio',
        '尤文斯塔比亚' : 'SS Juve Stabia',
        '锡耶纳' : 'Robur Siena',
        '雷吉纳' : 'Urbs Reggina 1914',
        '格罗瑟托' : 'US Grosseto 1912',
        '古比奥' : 'AS Gubbio 1910',
        '诺瑟里纳' : 'ASD Nocerina 1910',
        '阿尔比诺勒菲' : 'UC AlbinoLeffe',
        '皮亚琴察' : 'Piacenza Calcio 1919',
        '特里埃斯蒂纳' : 'US Triestina',
        '波图格鲁阿罗' : 'Portogruaro Calcio ASD',
        '波尔图' : 'FC Porto',
        '本菲卡' : 'SL Benfica',
        '里斯本竞技' : 'Sporting CP',
        '布拉加' : 'SC Braga',
        '里奥阿维' : 'Rio Ave FC',
        '查维斯' : 'GD Chaves',
        '沙维什' : 'GD Chaves',
        '马里迪莫' : 'CS Marítimo',
        '博阿维斯塔' : 'Boavista Porto FC',
        '吉马良斯' : 'Vitória Guimarães SC',
        '波尔蒂芒尼斯' : 'Portimonense SC',
        '波尔蒂芒斯' : 'Portimonense SC',
        '通德拉' : 'CD Tondela',
        '比兰尼塞斯' : 'CF Belenenses',
        '艾维斯' : 'Desportivo Aves',
        '阿维斯' : 'Desportivo Aves',
        '摩雷伦斯' : 'Moreirense FC',
        '摩雷伦塞' : 'Moreirense FC',
        '塞图巴尔' : 'Vitória Setúbal FC',
        '菲伦斯' : 'CD Feirense',
        '费伦斯' : 'CD Feirense',
        '费雷拉' : 'FC Paços de Ferreira',
        '埃斯托里尔' : 'GD Estoril Praia',
        '葡萄牙国民' : 'CD Nacional',
        '圣克拉拉' : 'CD Santa Clara',
        '圣塔克拉拉' : 'CD Santa Clara',
        '阿罗卡' : 'FC Arouca',
        '科英布拉大学' : 'Académica Coimbra',
        '科英布拉大' : 'Académica Coimbra',
        '马德拉' : 'CF União Madeira',
        '佩纳菲尔' : 'FC Penafiel',
        '佩纳菲耶尔' : 'FC Penafiel',
        '维森特' : 'Gil Vicente FC',
        '欧汉尼斯' : 'SC Olhanense',
        '贝拉马尔' : 'SC Beira-Mar',
        '圣彼得堡泽尼特' : 'Zenit St. Petersburg',
        '泽尼特' : 'Zenit St. Petersburg',
        '喀山红宝石' : 'Rubin Kazan',
        '喀山' : 'Rubin Kazan',
        '安郅马哈奇卡拉' : 'Anzhi Makhachkala',
        '安郅马哈奇' : 'Anzhi Makhachkala',
        '罗斯托夫' : 'FK Rostov',
        '莫斯科斯巴达' : 'Spartak Moscow',
        '莫斯巴达' : 'Spartak Moscow',
        '苏维埃之翼' : 'Krylya Sovetov Samara',
        '莫斯科迪纳摩' : 'Dinamo Moscow',
        '莫斯迪纳摩' : 'Dinamo Moscow',
        '莫斯科火车头' : 'Lokomotiv Moscow',
        '莫火车头' : 'Lokomotiv Moscow',
        '莫斯科中央陆军' : 'CSKA Moscow',
        '莫斯陆军' : 'CSKA Moscow',
        '乌法' : 'FK Ufa',
        '图拉' : 'Arsenal Tula',
        '图拉兵工厂' : 'Arsenal Tula',
        '克拉斯诺达尔' : 'FK Krasnodar',
        '克拉斯诺达' : 'FK Krasnodar',
        '乌拉尔' : 'Ural Yekaterinburg',
        '格罗兹尼捷列克' : 'Akhmat Grozny',
        '格罗兹尼艾' : 'Akhmat Grozny',
        '奥伦堡加索维克' : 'FK Orenburg',
        '奥伦堡加索' : 'FK Orenburg',
        '叶尼塞' : 'Enisey Krasnoyarsk',
        '辛历克' : 'Shinnik Yaroslavl',
        '托姆斯克' : 'Chertanovo Moscow',
        '托木斯克' : 'Chertanovo Moscow',
        '阿姆卡尔' : 'Amkar Perm',
        '图斯诺' : 'FK Tosno',
        'SKA恩纳吉亚' : 'SKA Khabarovsk',
        'SKA哈巴' : 'SKA Khabarovsk',
        '萨兰斯克' : 'Mordovia Saransk',
        '莫尔多维亚' : 'Mordovia Saransk',
        '加拉塔萨雷' : 'Galatasaray SK',
        '费内巴切' : 'Fenerbahce SK',
        '伊斯坦布尔' : 'Basaksehir',
        '贝西克塔斯' : 'Besiktas JK',
        '埃祖姆BB' : 'Büyüksehir Belediye Erzurumspor',
        '埃尔祖鲁姆' : 'Büyüksehir Belediye Erzurumspor',
        '特拉布宗体育' : 'Trabzonspor',
        '特拉布宗体' : 'Trabzonspor',
        '哥兹塔比' : 'Göztepe',
        '戈兹特普' : 'Göztepe',
        '锡瓦斯体育' : 'Sivasspor',
        '卡斯帕萨' : 'Kasimpasa',
        '开塞利体育' : 'Kayserispor',
        '马拉耶士邦' : 'Yeni Malatyaspor',
        '马拉蒂亚体' : 'Yeni Malatyaspor',
        '阿卡沙' : 'Akhisarspor',
        '阿克希萨尔' : 'Akhisarspor',
        '阿兰亚斯堡' : 'Alanyaspor',
        '阿拉尼亚体' : 'Alanyaspor',
        '布尔萨体育' : 'Bursaspor',
        '安塔利亚体育' : 'Antalyaspor',
        '安塔利亚体' : 'Antalyaspor',
        '科尼亚体育' : 'Konyaspor',
        '奥斯曼体育' : 'Osmanlispor FK',
        '根克勒比利吉' : 'Genclerbirligi Ankara',
        '卡拉比克体育' : 'Kardemir Karabükspor',
        '里泽斯堡' : 'Caykur Rizespor',
        '里泽体育' : 'Caykur Rizespor',
        '安卡拉古库' : 'MKE Ankaragücü',
        '安卡拉力量' : 'MKE Ankaragücü',
        '波卢斯堡' : 'Boluspor',
        '尤姆尼耶士邦' : 'Ümraniyespor',
        '巴里科斯士邦' : 'Balikesirspor',
        '加济安泰普体育' : 'Gaziantepspor',
        '艾丹亚斯普' : 'Adanaspor',
        '梅尔辛' : 'Mersin Idmanyurdu',
        '加辛塔BB' : 'Gazisehir Gaziantep Futbol Kulübü',
        '库班' : 'Kuban Krasnodar',
        '莫斯科鱼雷' : 'Torpedo Moscow',
        '伏尔加诺夫哥罗德' : 'Volga Nizhniy Novgorod',
        '阿拉尼亚' : 'Spartak Vladikavkaz',
        '奈兹克斯巴达' : 'Spartak Nalchik',
        '埃斯基谢希尔体育' : 'Eskisehirspor',
        '阿辛耶斯堡' : 'Kayseri Erciyesspor',
        '伊拉兹斯堡' : 'Elazigspor',
        '奥尔杜体育' : 'Orduspor',
        '布卡体育' : 'Bucaspor',
        'PSV埃因霍温' : 'PSV Eindhoven',
        '埃因霍温' : 'PSV Eindhoven',
        '阿贾克斯' : 'Ajax Amsterdam',
        '阿尔克马尔' : 'AZ Alkmaar',
        '费耶诺德' : 'Feyenoord Rotterdam',
        '乌德勒支' : 'FC Utrecht',
        '维迪斯' : 'Vitesse Arnhem',
        '海牙' : 'ADO Den Haag',
        '海伦芬' : 'SC Heerenveen',
        '兹沃勒' : 'PEC Zwolle',
        '赫拉克勒斯' : 'Heracles Almelo',
        'SBV精英' : 'Excelsior Rotterdam',
        '格罗宁根' : 'FC Groningen',
        '威廉二世' : 'Willem II Tilburg',
        '布雷达' : 'NAC Breda',
        '芬洛' : 'VVV-Venlo',
        '罗达JC' : 'Roda JC Kerkrade',
        '鹿特丹斯巴达' : 'Sparta Rotterdam',
        '特温特' : 'FC Twente Enschede',
        '阿贾克斯青年队' : 'Ajax Amsterdam',
        '福图纳锡塔德' : 'Fortuna Sittard',
        '福图纳' : 'Fortuna Sittard',
        '奈梅亨' : 'NEC Nijmegen',
        '格拉夫夏普' : 'De Graafschap Doetinchem',
        '埃因霍温青年队' : 'PSV Eindhoven U21',
        '特尔斯达' : 'SC Telstar',
        '埃门' : 'FC Emmen',
        '坎布尔' : 'SC Cambuur-Leeuwarden',
        '阿尔梅勒城' : 'Almere City FC',
        '马斯特里赫特' : 'MVV Maastricht',
        '登博思' : 'FC Den Bosch',
        '埃因霍温FC' : 'FC Eindhoven',
        '多德勒支' : 'FC Dordrecht',
        '福伦丹' : 'FC Volendam',
        '奥斯' : 'TOP Oss',
        '阿克马尔青年队' : 'AZ Alkmaar U21',
        '前进之鹰' : 'Go Ahead Eagles Deventer',
        '瓦尔韦克' : 'RKC Waalwijk',
        '海尔蒙特' : 'Helmond Sport',
        '乌德勒支青年队' : 'FC Utrecht U21',
        '亨克' : 'KRC Genk',
        '布鲁日' : 'Club Brugge KV',
        '安德莱赫特' : 'RSC Anderlecht',
        '标准列日' : 'Standard Liège',
        '奥斯坦德' : 'KV Oostende',
        '安特卫普' : 'Royal Antwerp FC',
        '聚尔特瓦雷赫姆' : 'SV Zulte Waregem',
        '瓦勒海姆' : 'SV Zulte Waregem',
        '贝弗伦' : 'Waasland-Beveren',
        '华斯兰德' : 'Waasland-Beveren',
        '圣图尔登' : 'Sint-Truidense VV',
        '圣特赖登' : 'Sint-Truidense VV',
        '色格拉布鲁日' : 'Cercle Brugge',
        '色格拉布鲁' : 'Cercle Brugge',
        '根特' : 'KAA Gent',
        '匹卢维兹' : 'Royal Excel Mouscron',
        '穆斯克龙' : 'Royal Excel Mouscron',
        '沙勒罗瓦' : 'RSC Charleroi',
        '欧本' : 'KAS Eupen',
        '科特赖克' : 'KV Kortrijk',
        '洛克伦' : 'KSC Lokeren',
        '洛默尔' : 'Lommel SK',
        '梅赫伦' : 'KV Mechelen',
        '韦斯特鲁' : 'KVC Westerlo',
        '韦斯特洛' : 'KVC Westerlo',
        '鲁瑟拉勒' : 'KSV Roeselare',
        '圣吉罗斯' : 'Royale Union Saint Gilloise',
        '圣吉罗斯联' : 'Royale Union Saint Gilloise',
        '蒂比兹' : 'AFC Tubize',
        '奥德赫维里' : 'Oud-Heverlee Leuven',
        '维吉克' : 'KFCO Beerschot Wilrijk',
        '维尔赖克' : 'KFCO Beerschot Wilrijk',
        '布隆德比' : 'Bröndby IF',
        '哥本哈根' : 'FC Copenhagen',
        '文德斯尔' : 'Vendsyssel FF',
        '奥尔堡' : 'Aalborg BK',
        '北西兰' : 'FC Nordsjaelland',
        '瓦埃勒' : 'Vejle Boldklub',
        '中日德兰' : 'FC Midtjylland',
        '桑德捷斯基' : 'SönderjyskE',
        '霍森斯' : 'AC Horsens',
        '兰纳斯' : 'Randers FC',
        '兰讷斯' : 'Randers FC',
        '奥胡斯' : 'Aarhus GF',
        '欧登塞' : 'Odense Boldklub',
        '埃斯比约' : 'Esbjerg fB',
        '霍布罗' : 'Hobro IK',
        'HB科治' : 'HB Köge',
        '科治' : 'HB Köge',
        '比利希尔星格' : 'FC Helsingör',
        '赫尔辛格' : 'FC Helsingör',
        '纳斯特维德' : 'Naestved Boldklub',
        '奈斯特韦兹' : 'Naestved Boldklub',
        '哈维德夫' : 'Hvidovre IF',
        '利恩比' : 'Lyngby BK',
        '灵比' : 'Lyngby BK',
        '维堡' : 'Viborg FF',
        '施克堡' : 'Silkeborg IF',
        '锡尔克堡' : 'Silkeborg IF',
        '萨姆松体育' : 'Samsunspor',
        '马尼萨体育' : 'Manisaspor',
        '罗兰法斯特' : 'Nyköbing FC',
        '尼克宾' : 'Nyköbing FC',
        '提斯特德' : 'Thisted FC',
        '齐斯泰兹' : 'Thisted FC',
        '腓特烈西亚' : 'FC Fredericia',
        '阿马盖尔' : 'BK Fremad Amager',
        '阿迈厄前进' : 'BK Fremad Amager',
        '罗斯基德' : 'FC Roskilde',
        '罗斯基勒' : 'FC Roskilde',
        '利尔斯' : 'KSK Lierse Kempenzonen',
        '蒙斯' : 'RAEC Mons',
        '比尔肖特' : 'Beerschot AC',
        '西希兰' : 'FC Vestsjaelland',
        '沃斯卡拉' : 'Vorskla Poltava',
        '奥德萨黑海人' : 'Chornomorets Odessa',
        '奥德萨黑海' : 'Chornomorets Odessa',
        '伊利奇维茨' : 'FK Mariupol',
        '马里乌波尔' : 'FK Mariupol',
        'D.奥林匹克' : 'Olimpik Donetsk',
        '顿涅奥林匹' : 'Olimpik Donetsk',
        'D.斯塔尔' : 'unknown',
        '维勒斯' : 'NK Veres Rivne',
        '基辅迪纳摩' : 'Dynamo Kyiv',
        '卢甘斯克黎明' : 'Zorya Lugansk',
        '卢甘斯克黎' : 'Zorya Lugansk',
        '卡帕迪' : 'Karpaty Lviv',
        '顿涅茨克矿工' : 'Shakhtar Donetsk',
        '顿涅矿工' : 'Shakhtar Donetsk',
        '奥利克桑德拉' : 'FK Oleksandria',
        '亚历山德里' : 'FK Oleksandria',
        '德斯纳' : 'Desna Chernihiv',
        '切尔尼希夫' : 'Desna Chernihiv',
        'FC利沃夫' : 'FK Lviv',
        '波塔华' : 'FK Poltava',
        '基辅兵工厂' : 'Arsenal Kyiv',
        'SK迪尼普' : 'SK Dnipro-1',
        '兹尔卡' : 'Zirka Kropyvnytsky',
        '第聂伯罗' : 'SK Dnipro-1',
        '沃林' : 'Volyn Lutsk',
        '霍维拉' : 'Hoverla Uzhhorod',
        '顿涅茨克冶金' : 'Metalurh Donetsk',
        '哈尔科夫金工' : 'Metalist 1925 Kharkiv',
        '扎波罗热冶金' : 'MFK Metalurh Zaporizhya',
        '塔夫里亚' : 'SK Tavriya Simferopol',
        '塞瓦斯托波尔' : 'FK Sevastopol',
        '克里夫巴斯' : 'Kryvbas Kryvyi Rih',
        '奥博隆' : 'Obolon-Brovar Kyiv',
        '斯基夫' : 'Skive IK',
        '布拉布特' : 'Brabrand IF',
        'AB哥本哈根' : 'Akademisk Boldklub',
        '布隆索伊' : 'Brönshöj Boldklub',
        '马利恩尔斯特' : 'Boldklubben Marienlyst',
        'FC菲恩' : 'FC Fyn',
        '布洛克胡斯' : 'Jammerbugt FC',
        '科尔丁IF' : 'Kolding IF',
        '卢宾' : 'Zaglebie Lubin',
        '卢宾扎格勒' : 'Zaglebie Lubin',
        '波兹南莱赫' : 'Lech Poznan',
        '莱赫波兹南' : 'Lech Poznan',
        '皮亚斯特' : 'Piast Gliwice',
        '斯拉斯克' : 'Slask Wroclaw',
        '史拉斯科' : 'Slask Wroclaw',
        '克拉科夫' : 'Wisla Kraków',
        '列治亚' : 'Lechia Gdansk',
        '哥罗纳' : 'Korona Kielce',
        '科罗纳凯尔' : 'Korona Kielce',
        '索斯诺维茨' : 'Zaglebie Sosnowiec',
        '比亚韦斯托克' : 'Jagiellonia Bialystok',
        '乔治罗尼亚' : 'Jagiellonia Bialystok',
        '莱格尼察' : 'Miedz Legnica',
        '华沙军团' : 'Legia Warszawa',
        '萨比利斯' : 'Górnik Zabrze',
        '扎布热矿工' : 'Górnik Zabrze',
        '华沙普洛克' : 'Wisla Plock',
        '普沃茨克' : 'Wisla Plock',
        '阿尔卡' : 'Arka Gdynia',
        '阿尔卡格丁' : 'Arka Gdynia',
        '克拉科维亚' : 'Cracovia Kraków',
        '施切钦波贡' : 'Pogon Szczecin',
        '什切青波贡' : 'Pogon Szczecin',
        '奥波莱' : 'Odra Opole',
        '霍吉尼赞卡' : 'Chojniczanka Chojnice',
        '苏瓦乌基' : 'Wigry Suwalki',
        '琴斯托霍瓦' : 'Rakow Czestochowa',
        '比托维亚' : 'Bytovia Bytow',
        'LKS尼切萨' : 'Bruk-Bet Termalica Nieciecza',
        '桑德克亚' : 'Sandecja Nowy Sacz',
        '博格丹卡' : 'Gornik Leczna',
        '罗切霍茹夫' : 'Ruch Chorzow',
        '保德比斯基' : 'Podbeskidzie Bielsko-Biala',
        '贝尔哈图夫' : 'GKS Belchatow',
        '萨维斯沙' : 'Zawisza Bydgoszcz',
        '维德祖罗茲' : 'Widzew Lodz',
        '华沙普罗尼亚' : 'Polonia Warsaw',
        'LKS洛迪兹' : 'LKS Lodz',
        '比托姆普罗尼亚' : 'Polonia Bytom',
        '布拉格斯拉维亚' : 'SK Slavia Prag',
        '布拉格斯拉' : 'SK Slavia Prag',
        '布拉格斯巴达' : 'AC Sparta Praha',
        '布拉斯巴达' : 'AC Sparta Praha',
        '布拉巴达' : 'AC Sparta Praha',
        '比尔森' : 'FC Viktoria Plzen',
        '皮尔森' : 'FC Viktoria Plzen',
        '兹林' : 'FC FASTAV Zlin',
        '特普利斯' : 'FK Teplice',
        '普日布拉姆' : '1.FK Pribram',
        '奥洛莫茨' : 'SK Sigma Olomouc',
        '奥洛穆茨' : 'SK Sigma Olomouc',
        '斯洛瓦科' : '1.FC Slovácko',
        '奥斯特拉瓦' : 'FC Banik Ostrava',
        '俄斯特拉发' : 'FC Banik Ostrava',
        '利贝雷茨' : 'FC Slovan Liberec',
        '波希米亚1905' : 'FC Bohemians Prag 1905',
        '波希米亚1' : 'FC Bohemians Prag 1905',
        '亚布洛内茨' : 'FK Jablonec',
        '雅布罗尼克' : 'FK Jablonec',
        '杜库拉' : 'FK Dukla Prag',
        '杜克拉' : 'FK Dukla Prag',
        '欧帕瓦' : 'Slezsky FC Opava',
        '奥帕瓦' : 'Slezsky FC Opava',
        '博雷斯拉夫' : 'FK Mladá Boleslav',
        '博莱斯拉夫' : 'FK Mladá Boleslav',
        '卡维纳' : 'MFK Karvina',
        '卡尔维纳' : 'MFK Karvina',
        '伊希拉瓦' : 'FC Vysocina Jihlava',
        '乌斯季' : 'Chojniczanka Chojnice',
        '布尔诺' : 'FC Zbrojovka Brno',
        '赫拉德茨克拉洛韦' : 'FC Hradec Králové',
        '布德约维茨迪纳摩' : 'SK Dynamo Ceske Budejovice',
        '兹诺伊摩' : '1.SC Znojmo',
        '济斯科夫' : 'FK Viktoria Zizkov',
        '赫尔辛基' : 'HJK Helsinki',
        '罗瓦涅米' : 'Rovaniemen Palloseura',
        '洛瓦涅米' : 'Rovaniemen Palloseura',
        '瓦萨' : 'Vaasan Palloseura',
        'VPS瓦萨' : 'Vaasan Palloseura',
        '洪卡' : 'FC Honka',
        '拉赫蒂' : 'FC Lahti',
        '埃尔维斯' : 'Ilves Tampere',
        '库普斯' : 'Kuopion Palloseura',
        '古比斯' : 'Kuopion Palloseura',
        '国际图尔库' : 'FC Inter Turku',
        '英特土尔库' : 'FC Inter Turku',
        '塞那乔恩' : 'SJK Seinäjoki',
        'SJK' : 'SJK Seinäjoki',
        '玛丽港' : 'IFK Mariehamn',
        '马里汉姆' : 'IFK Mariehamn',
        'TPS土尔库' : 'Turun Palloseura',
        'TPS土尔' : 'Turun Palloseura',
        'PS凯米' : 'PS Kemi Kings',
        'HIFK足球' : 'Helsinki IFK',
        'HIFK' : 'Helsinki IFK',
        'EIF埃克纳斯' : 'Ekenäs IF',
        '埃克奈斯I' : 'Ekenäs IF',
        'KPV科高拉' : 'Kokkolan Pallo-Veikot',
        'KPV科科' : 'Kokkolan Pallo-Veikot',
        '哈卡' : 'FC Haka',
        '查路' : 'FF Jaro',
        '科特卡' : 'FC KTP',
        'KTP' : 'FC KTP',
        'AC奥卢' : 'AC Oulu',
        'AC卡亚尼' : 'AC Kajaani',
        '韦斯屈莱' : 'JJK Jyväskylä',
        '克鲁比04' : 'Klubi 04 Helsinki',
        'PK35万塔' : 'Pallokerho-35',
        '迈帕' : 'Myllykosken Pallo -47',
        '坦佩雷' : 'Tampere United',
        '格力夫克' : 'Grankulla IFK',
        '格尼斯坦' : 'IF Gnistan',
        'ops奥鲁' : 'Oulun Palloseura',
        '爵士FC' : 'FC Jazz Juniorit',
        'MP米凯利' : 'Mikkelin Palloilijat',
        '维夫克' : 'Vaasa IFK',
        '吉普' : 'JIPPO Joensuu',
        '维京吉特' : 'FC Viikingit',
        '库迪皮' : 'FC KTP',
        '哈美林纳' : 'FC Hämeenlinna',
        '波帕' : 'Porin Palloilijat',
        '埃斯波' : 'FC Espoo',
        'TPV谭柏利' : 'Tampereen Pallo-Veikot',
        '哈特堡格' : 'TSV Hartberg',
        '哈特贝格' : 'TSV Hartberg',
        '奥地利卢斯特瑙' : 'SC Austria Lustenau',
        '奥卢斯特瑙' : 'SC Austria Lustenau',
        '列特' : 'SV Ried',
        '卡芬堡' : 'SV Kapfenberg',
        '因斯布鲁克' : 'FC Wacker Innsbruck',
        'FAC维也纳' : 'Floridsdorfer AC',
        'FAC维也' : 'Floridsdorfer AC',
        '列弗灵' : 'FC Liefering',
        '列夫林' : 'FC Liefering',
        '马纳' : 'SC Wiener Neustadt',
        'SC维也纳' : 'SC Wiener Neustadt',
        'BW林茨' : 'FC Blau Weiss Linz',
        '蓝白林茨' : 'FC Blau Weiss Linz',
        '华登斯' : 'WSG Wattens',
        '瓦腾斯' : 'WSG Wattens',
        '瓦克蒂罗尔B队' : 'FC Wacker Innsbruck II',
        '因斯布B队' : 'FC Wacker Innsbruck II',
        'SV霍恩' : 'SV Horn',
        'LASK林茨' : 'LASK Linz',
        'LASK林' : 'LASK Linz',
        '克拉根福' : 'SK Austria Klagenfurt',
        '奥地利克拉' : 'SK Austria Klagenfurt',
        '奥克拉根福' : 'SK Austria Klagenfurt',
        'PSV萨尔斯堡' : 'PSV Salzburg',
        '圣珀尔滕' : 'SKN St. Pölten',
        '马特斯堡' : 'SV Mattersburg',
        '阿尔特阿赫' : 'SC Rheindorf Altach',
        '第一维也纳' : 'First Vienna FC',
        '帕多夫' : 'SC/ESV Parndorf',
        'FC卢斯特瑙' : 'FC Lustenau',
        '格罗迪SV' : 'SV Grödig',
        '沃尔贝格' : 'Wolfsberger AC',
        '格拉科恩' : 'FC Gratkorn',
        '阿德米拉' : 'FC Admira Wacker Mödling',
        '萨尔茨堡' : 'Red Bull Salzburg',
        '格拉茨风暴' : 'SK Sturm Graz',
        '奥地利维也纳' : 'Austria Vienna',
        '奥地利维也' : 'Austria Vienna',
        '维也纳快速' : 'Rapid Vienna',
        '广州恒大淘宝' : 'Guangzhou Evergrande Taobao',
        '上海上港集团' : 'Shanghai SIPG',
        '北京中赫国安' : 'Beijing Sinobo Guoan',
        '天津权健' : 'Tianjin Quanjian',
        '大连一方' : 'Dalian Yifang',
        '江苏苏宁易购' : 'Jiangsu Suning',
        '山东鲁能泰山' : 'Shandong Luneng Taishan',
        '上海绿地申花' : 'Shanghai Greenland Shenhua',
        '长春亚泰' : 'Changchun Yatai',
        '广州富力' : 'Guangzhou R&F',
        '河北华夏幸福' : 'Hebei China Fortune',
        '天津泰达亿利' : 'Tianjin Teda',
        '北京人和' : 'Beijing Renhe',
        '河南建业' : 'Henan Jianye',
        '贵州恒丰' : 'Guizhou Hengfeng',
        '重庆斯威' : 'Chongqing Dangdai Lifan',
        '武汉卓尔' : 'Wuhan Zall',
        '深圳佳兆业' : 'Shenzhen FC',
        '杭州绿城' : 'Zhejiang Greentown',
        '上海申鑫' : 'Shanghai Shenxin',
        '梅县铁汉生态' : 'Meizhou Meixian Techand',
        '辽宁沈阳开新' : 'Liaoning FC',
        '梅州客家' : 'Meizhou Hakka',
        '石家庄永昌' : 'Shijiazhuang Ever Bright',
        '北京北控燕京' : 'Beijing Enterprises',
        '内蒙古中优' : 'Nei Mongol Zhongyou',
        '浙江毅腾轻纺城' : 'Zhejiang Yiteng',
        '黑龙江火山鸣泉' : 'Heilongjiang Lava Spring',
        '延边富德' : 'Yanbian Funde',
        '大连超越' : 'Dalian Transcendence',
        '青岛黄海' : 'Qingdao Huanghai',
        '新疆天山雪豹' : 'Xinjiang Tianshan Leopard',
        '四川安纳普尔那' : 'Sichuan Longfor',
        '南通支云' : 'Nantong Zhiyun',
        '湖南湘涛华莱' : 'Hunan Billows',
        '深圳人人' : 'Shenzhen Renren',
        '镇江文旅华萨' : 'Zhenjiang Huasa',
        '苏州东吴' : 'Suzhou Dongwu',
        '四川九牛' : 'Sichuan Jiuniu',
        '福建天信' : 'Fujian Tianxin',
        '江西联盛' : 'Jiangxi Liansheng',
        '海南FC' : 'Hainan Boying',
        '丽江飞虎' : 'Yunnan Feihu',
        '深圳鹏城' : 'Shenzhen Pengcheng',
        '上海申梵' : 'Shanghai Sunfun',
        '合肥桂冠' : 'Hefei Guiguan',
        '大阪樱花' : 'Cerezo Osaka',
        '浦和红钻' : 'Urawa Red Diamonds',
        '神户胜利船' : 'Vissel Kobe',
        '川崎前锋' : 'Kawasaki Frontale',
        '鸟栖沙岩' : 'Sagan Tosu',
        '鹿岛鹿角' : 'Kashima Antlers',
        '名古屋鲸八' : 'Nagoya Grampus',
        '柏太阳神' : 'Kashiwa Reysol',
        '大阪钢巴' : 'Gamba Osaka',
        '广岛三箭' : 'Sanfrecce Hiroshima',
        '东京FC' : 'FC Tokyo',
        'FC东京' : 'FC Tokyo',
        '横滨水手' : 'Yokohama F. Marinos',
        '磐田喜悦' : 'Júbilo Iwata',
        '磐田山叶' : 'Júbilo Iwata',
        '清水鼓动' : 'Shimizu S-Pulse',
        '清水心跳' : 'Shimizu S-Pulse',
        '湘南海洋' : 'Shonan Bellmare',
        '湘南比马' : 'Shonan Bellmare',
        '札幌冈萨多' : 'Hokkaido Consadole Sapporo',
        '仙台维加泰' : 'Vegalta Sendai',
        '长崎航海' : 'V-Varen Nagasaki',
        '大宫松鼠' : 'Omiya Ardija',
        '千叶市原' : 'JEF United Chiba',
        '松本山雅' : 'Matsumoto Yamaga FC',
        '德岛漩涡' : 'Tokushima Vortis',
        '新泻天鹅' : 'Albirex Niigata',
        '福冈黄蜂' : 'Avispa Fukuoka',
        '横滨FC' : 'Yokohama FC',
        '冈山绿雉' : 'Fagiano Okayama',
        '东京绿茵' : 'Tokyo Verdy',
        '甲府风林' : 'Ventforet Kofu',
        '大分三神' : 'Oita Trinita',
        '山形山神' : 'Montedio Yamagata',
        '京都不死鸟' : 'Kyoto Sanga FC',
        '熊本深红' : 'Roasso Kumamoto',
        '山口' : 'Renofa Yamaguchi FC',
        '山口雷诺法' : 'Renofa Yamaguchi FC',
        '爱媛FC' : 'Ehime FC',
        '町田泽维亚' : 'FC Machida Zelvia',
        '金泽塞维根' : 'Zweigen Kanazawa',
        '岐阜FC' : 'FC Gifu',
        'FC岐阜' : 'FC Gifu',
        '赞岐釜玉海' : 'Kamatamare Sanuki',
        '水户蜀葵' : 'Mito HollyHock',
        '枥木SC' : 'Tochigi SC',
        '全北现代' : 'Jeonbuk Hyundai Motors FC',
        '蔚山现代' : 'Ulsan Hyundai',
        '济州联队' : 'Jeju United FC',
        '水原三星' : 'Suwon Samsung Bluewings FC',
        '首尔FC' : 'FC Seoul',
        'FC首尔' : 'FC Seoul',
        '尚州尚武凤凰' : 'Sangju Sangmu FC',
        '尚州尚武F' : 'Sangju Sangmu FC',
        '江原FC' : 'Gangwon FC',
        '全南天龙' : 'Jeonnam Dragons FC',
        '大邱FC' : 'Daegu FC',
        '庆南FC' : 'Gyeongnam FC',
        '浦项制铁' : 'FC Pohang Steelers',
        '仁川联合' : 'Incheon United FC',
        '仁川联队' : 'Incheon United FC',
        '牙山木槿花' : 'Asan Mugunghwa FC',
        '警察俱乐部' : 'Asan Mugunghwa FC',
        '水原FC' : 'Suwon FC',
        '大田市民' : 'Daejeon Citizen FC',
        '釜山偶像' : 'Busan IPark FC',
        '首尔衣恋' : 'Seoul E-Land FC',
        '城南FC' : 'Seongnam FC',
        '安阳FC' : 'FC Anyang',
        'FC安阳' : 'FC Anyang',
        '富川1995' : 'Bucheon FC 1995',
        '富川199' : 'Bucheon FC 1995',
        '安山小绿人' : 'Ansan Greeners FC',
        '安山新军' : 'Ansan Greeners FC',
        '光州FC' : 'Gwangju FC',
        '墨尔本城' : 'Melbourne City FC',
        '悉尼FC' : 'Sydney FC',
        '布里斯班狮吼' : 'Brisbane Roar',
        '西悉尼漫步者' : 'Western Sydney Wanderers',
        '惠灵顿凤凰' : 'Wellington Phoenix',
        '墨尔本胜利' : 'Melbourne Victory',
        '珀斯光荣' : 'Perth Glory',
        '纽卡斯尔喷气机' : 'Newcastle United Jets',
        '阿德莱德联' : 'Adelaide United',
        '中央海岸水手' : 'Central Coast Mariners',
        '阿斯隆' : 'Athlone Town AFC',
        '阿斯隆城' : 'Athlone Town AFC',
        '布雷' : 'Bray Wanderers',
        '波希米亚人' : 'Bohemian Football Club Dublin',
        '德里城' : 'Derry City',
        '德利城' : 'Derry City',
        '邓多克' : 'Dundalk FC',
        '登克尔克' : 'Dundalk FC',
        '沃特福德联合' : 'Waterford FC',
        '沃特福德F' : 'Waterford FC',
        '科克城' : 'Cork City FC',
        '沙姆洛克流浪' : 'Shamrock Rovers',
        '沙姆洛克流' : 'Shamrock Rovers',
        '圣帕特里克' : 'St. Patricks Athletic',
        '斯莱戈流浪' : 'Sligo Rovers',
        '利默里克' : 'Limerick FC',
        '都柏林大学' : 'University College Dublin',
        '费恩哈普' : 'Finn Harps',
        '谢尔伯恩' : 'Shelbourne FC',
        '德罗赫达联' : 'Drogheda United FC',
        '朗福德城' : 'Longford Town FC',
        '戈尔韦' : 'Galway United FC',
        '戈尔韦联队' : 'Galway United FC',
        '卡宾迪利' : 'Cabinteely FC',
        '卡宾提利' : 'Cabinteely FC',
        '科布漫步者队' : 'Cobh Ramblers FC',
        '科布漫步者' : 'Cobh Ramblers FC',
        '韦克斯福德青年' : 'Wexford FC',
        '韦克斯福德' : 'Wexford FC',
        '芬盖尔竞技' : 'Sporting Fingal',
        '拉夫尼茨' : 'SV Lafnitz',
        '苏柏芬特' : 'FC Juniors OÖ',
        '帕兴青年' : 'FC Juniors OÖ',
        '奥地利维也纳青年' : 'Young Violets Austria Wien',
        '奥维也B队' : 'Young Violets Austria Wien',
        '斯太尔前进' : 'SK Vorwärts Steyr',
        '沙姆洛克流浪B队' : 'Shamrock Rovers U20',
        'SD戈尔韦' : 'Galway United FC',
        '摩维联' : 'Mervue United A.F.C.',
        '莫纳汉联队' : 'Mervue United A.F.C.',
        '罗森博格' : 'Rosenborg BK',
        '布兰' : 'SK Brann',
        '海于格松' : 'FK Haugesund',
        '莫尔德' : 'Molde FK',
        '萨尔普斯堡' : 'Sarpsborg 08 FF',
        '兰赫姆' : 'Ranheim IL',
        '兰黑姆' : 'Ranheim IL',
        '特罗姆瑟' : 'Tromsö IL',
        '克里斯蒂安松' : 'Kristiansund BK',
        '克里斯蒂安' : 'Kristiansund BK',
        '瓦勒伦加' : 'Valerenga Oslo',
        '奥德' : 'Odds BK',
        '斯特罗姆加斯特' : 'Strømsgodset IF',
        '斯托姆加斯' : 'Strømsgodset IF',
        '博德闪耀' : 'FK Bodø/Glimt',
        '博多格林特' : 'FK Bodø/Glimt',
        '利勒斯特罗姆' : 'Lilleström SK',
        '利勒斯特罗' : 'Lilleström SK',
        '斯塔贝克' : 'Stabaek IF',
        '斯达' : 'IK Start',
        '桑纳菲尤尔' : 'Sandefjord Fotball',
        '奥勒松' : 'Aalesunds FK',
        '松达尔' : '	Sogndal IL',
        '姆延达伦' : 'Mjøndalen',
        '莫达伦' : 'Mjøndalen',
        '维京' : 'Viking Stavanger',
        '基沙' : 'Ullensaker/Kisa',
        '基萨' : 'Ullensaker/Kisa',
        '特罗姆斯达伦' : 'Tromsdalen',
        '特罗姆斯达' : 'Tromsdalen',
        '康斯文格' : 'Kongsvinger IL',
        '孔斯温厄尔' : 'Kongsvinger IL',
        '桑内斯' : 'Sandnes Ulf',
        '尼斯特索特拉' : 'Nest-Sotra IL',
        '内斯特索特' : 'Nest-Sotra IL',
        '阿萨纳' : 'Asane Fotball',
        '奥桑内' : 'Asane Fotball',
        '格里姆斯塔' : '	FK Jerv',
        '耶尔夫' : '	FK Jerv',
        '诺托登' : 'Notodden',
        '汉坎' : 'Hamarkameratene',
        '费洛罗' : 'Florö SK',
        '弗卢勒' : 'Florö SK',
        '斯托曼' : 'Strømmen IF',
        '利云格尔' : 'Levanger FK',
        '莱旺厄尔' : 'Levanger FK',
        '赫纳福斯' : 'Hönefoss BK',
        '腓特烈斯塔' : 'Fredrikstad FK',
        '阿伦达尔' : 'FK Arendal',
        '埃尔沃吕姆' : 'Elverum Fotball',
        '赫德' : 'IL Hödd',
        '布莱尼' : 'Bryne FK',
        '库弗姆' : 'KFUM-Kameratene Oslo',
        '诺霍斯' : 'Raufoss IL',
        '拜鲁姆' : 'Baerum SK',
        '弗洛' : 'Follo FK',
        '阿尔塔' : 'Alta IF',
        '瓦尔德豪根桑' : 'Vard Haugesund',
        '洛夫汉姆' : 'unknown',
        '尼堡桑德' : 'Nybergsund',
        '兰达伯格' : 'Randaberg IL',
        '阿斯克尔' : 'Asker Fotball',
        '莫斯' : 'Moss FK',
        '利恩' : 'FK Lyn',
        '群马温泉' : 'ThespaKusatsu Gunma Jugend',
        '北九州向日葵' : 'Giravanz Kitakyushu',
        '鸟取希望' : 'Gainare Tottori',
        '富山胜利' : 'Toyama',
        '高阳Hi' : 'Goyang Zaicro FC',
        '忠州胡穆尔' : 'Chungju Hummel FC',
        '黃金海岸联' : 'Gold Coast United',
        '北昆士兰狂暴' : 'Northern Fury FC',
        '科洛科洛': 'CSD Colo Colo',
        '智利大学': 'Club Universidad de Chile',
        '天主大学': 'CD Universidad Católica',
        '智利天主大': 'CD Universidad Católica',
        '伊瓦顿': 'CD Everton',
        '埃弗顿比尼': 'CD Everton',
        '康塞普西翁大学': 'Universidad Concepción',
        '康塞普西翁': 'Universidad Concepción',
        '安托法加斯塔': 'Club de Deportes Antofagasta',
        '安托法加斯': 'Club de Deportes Antofagasta',
        '西班牙联合': 'Unión Española',
        '巴勒斯坦人': 'CD Palestino',
        '瓦奇巴托': 'Huachipato FC',
        '基约塔': 'CD San Luis de Quillota',
        '圣路易斯基': 'CD San Luis de Quillota',
        '特木科': 'Deportes Temuco',
        '特木科体育': 'Deportes Temuco',
        '奥伊金斯': "CD O'Higgins",
        '奥达科斯意大利人': 'Audax Italiano',
        '奥达科斯意': 'Audax Italiano',
        '伊基克体育': 'Club Deportes Iquique',
        '拉卡莱拉联合': 'Unión La Calera',
        '克里科': 'CDP Curicó Unido',
        '库里科联队': 'CDP Curicó Unido',
        '弗拉门戈': 'Clube de Regatas do Flamengo',
        '帕尔梅拉斯': 'Sociedade Esportiva Palmeiras',
        '格雷米奥': 'Grêmio Foot-Ball Porto Alegrense',
        '桑托斯': 'Santos FC',
        '克鲁塞罗': 'Cruzeiro Esporte Clube',
        '科林蒂安': 'Sport Club Corinthians Paulista',
        '圣保罗': 'São Paulo Futebol Clube',
        '巴西国际': 'Sport Club Internacional',
        '米内罗竞技': 'Clube Atlético Mineiro',
        '米涅罗竞技': 'Clube Atlético Mineiro',
        '瓦斯科达伽马': 'Club de Regatas Vasco da Gama',
        '瓦斯科达伽': 'Club de Regatas Vasco da Gama',
        '巴伊亚': 'Esporte Clube Bahia',
        '维多利亚': 'Esporte Clube Vitória',
        '博塔弗戈': 'Botafogo Rio de Janeiro',
        '巴拉纳竞技': 'Atlético Paranaense',
        '弗鲁米嫩塞': 'Fluminense Football Club',
        '沙佩科恩斯': 'Associação Chapecoense de Futebol',
        '累西腓体育': 'Sport Club do Recife',
        '米内罗美洲': 'América Futebol Clube (MG)',
        '米涅罗美洲': 'América Futebol Clube (MG)',
        '塞阿拉': 'Ceará Sporting Club',
        '塞阿腊': 'Ceará Sporting Club',
        '巴拉纳': 'Paraná Clube',
        '戈亚斯': 'Goiás Esporte Clube',
        'CR巴西': 'Clube de Regatas Brasil (AL)',
        '科里蒂巴': 'Coritiba Foot Ball Club',
        '阿瓦伊': 'Avaí Futebol Clube (SC)',
        '阿拉戈亚诺体育队': 'Centro Sportivo Alagoano (AL)',
        'CSA阿拉': 'Centro Sportivo Alagoano (AL)',
        '费古埃伦斯': 'Figueirense Futebol Clube',
        '隆德里纳': 'Londrina Esporte Clube (PR)',
        '庞特普雷塔': 'Associação Atlética Ponte Preta',
        '福塔雷萨': 'Fortaleza Esporte Clube',
        '尤文图德': 'Esporte Clube Juventude',
        '巴西青年人': 'Esporte Clube Juventude',
        '克里西乌马': 'Criciúma Esporte Clube',
        '克里丘马': 'Criciúma Esporte Clube',
        '欧斯蒂': 'Oeste Futebol Clube (SP)',
        '欧斯特': 'Oeste Futebol Clube (SP)',
        '维拉诺瓦': 'Vila Nova Futebol Clube (GO)',
        '圣本图': 'Esporte Clube São Bento (SP)',
        '巴西瓜拉尼': 'Guarani Futebol Clube (SP)',
        '帕桑度': 'Paysandu Sport Club',
        '派桑杜': 'Paysandu Sport Club',
        '戈亚尼亚竞技': 'AC Goianiense (GO)',
        '戈亚尼恩斯': 'AC Goianiense (GO)',
        '布拉希尔佩洛塔斯': 'Grêmio Esportivo Brasil (RS)',
        '佩洛塔斯': 'Grêmio Esportivo Brasil (RS)',
        '伊图乌塔巴': 'Boa Esporte Clube (MG)',
        '博阿体育': 'Boa Esporte Clube (MG)',
        '桑帕约科雷亚': 'Sampaio Corrêa Futebol Clube (MA)',
        '桑帕约科雷': 'Sampaio Corrêa Futebol Clube (MA)',
        '亚特兰大联': 'Atlanta United FC',
        '亚特兰联队': 'Atlanta United FC',
        '洛杉矶FC': 'Los Angeles FC',
        '多伦多FC': 'Toronto FC',
        '洛杉矶银河': 'Los Angeles Galaxy',
        '波特兰伐木工': 'Portland Timbers',
        '波特兰伐木': 'Portland Timbers',
        '华盛顿联': 'D.C. United',
        '华盛顿联队': 'D.C. United',
        '西雅图海湾人': 'Seattle Sounders FC',
        '西雅图音速': 'Seattle Sounders FC',
        '纽约城': 'New York City FC',
        '纽约红牛': 'New York Red Bulls',
        '芝加哥火焰': 'Chicago Fire',
        '哥伦布机员': 'Columbus Crew SC',
        '费城联合': 'Philadelphia Union',
        '堪萨斯城竞技': 'Sporting Kansas City',
        '堪萨斯竞技': 'Sporting Kansas City',
        '奥兰多城': 'Orlando City SC',
        '蒙特利尔冲击': 'Montreal Impact',
        '蒙特利尔冲': 'Montreal Impact',
        '科罗拉多急流': 'Colorado Rapids',
        '科罗拉多急': 'Colorado Rapids',
        '达拉斯FC': 'FC Dallas',
        'FC达拉斯': 'FC Dallas',
        '圣何塞地震': 'San Jose Earthquakes',
        '温哥华白帽': 'Vancouver Whitecaps',
        '明尼苏达联': 'Minnesota United FC',
        '新英格兰革命': 'New England Revolution',
        '新英格兰革': 'New England Revolution',
        '休斯顿迪纳摩': 'Houston Dynamo',
        '休斯顿迪纳': 'Houston Dynamo',
        '皇家盐湖城': 'Real Salt Lake City',
        '马尔默': 'Malmö FF',
        'AIK索尔纳': 'AIK Solna',
        '索尔纳': 'AIK Solna',
        '佐加顿斯': 'Djurgardens IF',
        '北雪平': 'IFK Norrköping',
        '厄斯特松德': 'Östersunds FK',
        '赫根': 'BK Häcken',
        '哈马比': 'Hammarby IF',
        '埃尔夫斯堡': 'IF Elfsborg',
        '卡尔马': 'Kalmar FF',
        '厄勒布鲁': 'Örebro SK',
        'IFK哥德堡': 'IFK Göteborg',
        '哥德堡': 'IFK Göteborg',
        '松兹瓦尔': 'GIF Sundsvall',
        '天狼星': 'IK Sirius',
        '特雷勒堡': 'Trelleborgs FF',
        '达尔库德': 'Dalkurd FF',
        '达尔库尔德': 'Dalkurd FF',
        '布鲁马波卡纳': 'IF Brommapojkarna',
        '布鲁马波卡': 'IF Brommapojkarna',
        '赫尔辛堡': 'Helsingborgs IF',
        '延雪平': 'Jönköpings Södra IF',
        '埃斯基尔斯蒂纳': 'Athletic Eskilstuna',
        '埃斯基尔斯': 'Athletic Eskilstuna',
        '哈尔姆斯塔德': 'Halmstads BK',
        '哈尔姆斯塔': 'Halmstads BK',
        '韦纳穆': 'IFK Värnamo',
        '法尔肯堡': 'Falkenbergs FF',
        '厄斯特什': 'Östers IF',
        '奥斯达': 'Östers IF',
        '哥德堡盖斯': 'GAIS Göteborg',
        '加尔斯': 'GAIS Göteborg',
        '奥尔格里特': 'Örgryte IS',
        '耶夫勒': 'Gefle IF',
        '挪臂': 'Norrby IF',
        '诺尔比': 'Norrby IF',
        '迪格弗斯': 'Degerfors IF',
        '代格福什': 'Degerfors IF',
        '费里': 'IK Frej',
        '弗雷杰': 'IK Frej',
        '瓦尔贝里': 'Varbergs BoIS',
        '布莱格': 'IK Brage',
        '兰斯科罗纳': 'Landskrona BoIS',
        '兰斯克鲁纳': 'Landskrona BoIS',
        '凯尔特人': 'Celtic FC',
        '格拉斯哥流浪者': 'Rangers FC',
        '格拉流浪者': 'Rangers FC',
        '哈茨': 'Heart of Midlothian FC',
        '希伯尼安': 'Hibernian FC',
        '阿伯丁': 'Aberdeen FC',
        '圣约翰斯通': 'St. Johnstone FC',
        '基尔马诺克': 'Kilmarnock FC',
        '基马诺克': 'Kilmarnock FC',
        '马瑟韦尔': 'Motherwell FC',
        '邓迪FC': 'Dundee FC',
        '利云斯顿': 'Livingston FC',
        '利文斯顿': 'Livingston FC',
        '圣米伦': 'St. Mirren FC',
        '汉密尔顿': 'Hamilton Academical FC',
        '哈密尔顿': 'Hamilton Academical FC',
        '邓迪联': 'Dundee United FC',
        '罗斯郡': 'Ross County FC',
        '邓弗姆林': 'Dunfermline Athletic FC',
        '帕尔蒂克': 'Partick Thistle FC',
        '因弗内斯': 'Inverness Caledonian Thistle FC',
        '法基克': 'Falkirk FC',
        '摩顿': 'Greenock Morton FC',
        '南后': 'Queen of the South FC',
        '艾尔联': 'Ayr United FC',
        '艾洛亚竞技': 'Alloa Athletic FC',
        '年轻人': 'BSC Young Boys',
        '巴塞尔': 'FC Basel 1893',
        '草蜢': 'Grasshopper Club Zurich',
        '苏黎世': 'FC Zürich',
        '锡永': 'FC Sion',
        '卢塞恩': 'FC Luzern',
        '卢加诺': 'FC Lugano',
        '图恩': 'FC Thun',
        '圣加仑': 'FC St. Gallen 1879',
        '纳沙泰尔': 'Neuchâtel Xamax FCS',
        '洛桑': 'FC Lausanne-Sport',
        '塞尔维特': 'Servette FC',
        '阿劳': 'FC Aarau',
        '切阿索': 'FC Chiasso',
        '基亚索': 'FC Chiasso',
        '瓦杜兹': 'FC Vaduz',
        '温特图尔': 'FC Winterthur',
        '沙夫豪森': 'FC Schaffhausen',
        '韦尔1900': 'FC Wil 1900',
        '韦尔': 'FC Wil 1900',
        '拉珀斯维尔': 'FC Rapperswil-Jona',
        '克里恩斯': 'SC Kriens',
        '克林斯': 'SC Kriens',
        '布加勒斯特星': 'FCS Bucharest',
        '布加勒星队': 'FCS Bucharest',
        '克卢日': 'CFR Cluj',
        'CS卡拉奥华大学': 'CS Universitatea Craiova',
        'CSU克拉': 'CS Universitatea Craiova',
        '维托鲁康斯坦萨': 'FC Viitorul',
        '维托鲁康斯': 'FC Viitorul',
        '布加勒斯特迪那摩': 'Dinamo Bukarest',
        '布加迪纳摩': 'Dinamo Bukarest',
        '久尔久': 'Astra Giurgiu',
        '阿斯特拉': 'Astra Giurgiu',
        'CSMS雅西': 'FC Politehnica Iasi',
        'CSMS雅': 'FC Politehnica Iasi',
        '康戈迪亚齐安': 'Concordia Chiajna',
        '康戈迪亚': 'Concordia Chiajna',
        '舍佩斯': 'Sepsi Sf. Gheorghe',
        '塞普西': 'Sepsi Sf. Gheorghe',
        '波图森尼': 'FC Botosani',
        '博托沙尼': 'FC Botosani',
        '沃伦塔利': 'FC Voluntari',
        '沃伦塔里': 'FC Voluntari',
        '赫曼施塔特': 'FC Hermannstadt',
        '加斯梅登': 'Gaz Metan Medias',
        '克勒拉希': 'Dunarea Calarasi',
        '多瑙河克勒': 'Dunarea Calarasi',
        '萨格勒布迪纳摩': 'GNK Dinamo Zagreb',
        '斯普利特海杜克': 'HNK Hajduk Split',
        '里耶卡': 'HNK Rijeka',
        '奥斯积克': 'NK Osijek',
        '国际萨佩斯克': 'NK Inter Zapresic',
        '萨格勒布火车头': 'NK Lokomotiva Zagreb',
        '斯拉文': 'Slaven Belupo Koprivnica',
        '依斯特拉': 'NK Istra 1961',
        'HNK戈里察': 'HNK Gorica',
        '鲁达士': 'NK Rudes',
        '贝尔格莱德红星': 'Red Star Belgrade',
        '贝尔格莱德游击': 'FK Partizan Belgrade',
        '伏伊伏丁那': 'FK Vojvodina Novi Sad',
        '古拉瑞奇': 'FK Cukaricki',
        '苏波迪查': 'FK Spartak Subotica',
        '沃日多瓦茨': 'FK Vozdovac',
        '尼斯拉德尼基': 'FK Radnicki Nis',
        '纳普里达克': 'FK Napredak Krusevac',
        '泽蒙': 'FK Zemun',
        '马拉多特': 'FK Mladost Lucani',
        '帕兰卡': 'OFK Backa',
        '苏杜利察': 'FK Radnik Surdulica',
        '拉德': 'FK Rad',
        '马茨瓦': 'FK Macva Sabac',
        '普莱特尔': 'FK Proleter Novi Sad',
        '维兰捷': 'Dinamo Vranje',
        '贝尔谢巴夏普尔': 'Hapoel Beer Sheva',
        '特拉维夫马卡比': 'Maccabi Tel Aviv',
        '海法马卡比': 'Maccabi Haifa',
        '耶路撒冷贝塔': 'Beitar Jerusalem',
        '佩塔提克瓦马卡比': 'Maccabi Petah Tikva',
        '海法夏普尔': 'Hapoel Haifa',
        '比尼萨赫宁': 'Ihud Bnei Sakhnin',
        '特拉维夫夏普尔': 'Hapoel Tel Aviv',
        '谢莫纳夏普尔': 'Ironi Kiryat Shmona',
        '赖阿南纳夏普尔': 'Hapoel Raanana',
        '比尼叶胡达': 'Bnei Yehuda Tel Aviv',
        '尼坦耶马卡比': 'Maccabi Netanya',
        '阿什杜德': 'FC Ashdod',
        '哈迪拉': 'Hapoel Hadera',
        '卢多戈雷茨': 'PFK Ludogorets Razgrad',
        '索菲亚中央陆军': 'CSKA Sofia',
        '索菲亚利夫斯基': 'Levski Sofia',
        '旧扎戈拉贝罗': 'PFC Beroe Stara Zagora',
        '普罗夫迪夫博泰夫': 'Botev Plovdiv',
        '普夫迪夫火车头': 'Lokomotiv Plovdiv',
        '查洛摩利': 'Cherno More Varna',
        '依塔': 'Etar Veliko Tarnovo',
        '索非亚斯拉维亚': 'Slavia Sofia',
        '华拉特莎': 'OFC Botev Vratsa',
        '瑟特曼维里索菲亚': 'Septemvri Sofia',
        '多瑙': 'FK Dunav Ruse',
        '维多萨': 'FK Vitosha Bistritsa',
        'VS萨格拉': 'FK Vereya Stara Zagora',
        '博卡青年': 'Club Atlético Boca Juniors',
        '阿根廷独立': 'Club Atlético Independiente',
        '河床': 'Club Atlético River Plate',
        '竞技俱乐部': 'Racing Club',
        '圣洛伦索': 'Club Atlético San Lorenzo de Almagro',
        '拉努斯': 'Club Atlético Lanús',
        '萨斯菲尔德': 'Club Atlético Vélez Sarsfield',
        '戈多伊克鲁斯': 'Club Deportivo Godoy Cruz',
        '戈多伊克鲁': 'Club Deportivo Godoy Cruz',
        '科隆竞技': 'Club Atlético Colón',
        '防御与正义': 'Defensa y Justicia',
        '防卫与正义': 'Defensa y Justicia',
        '罗萨里奥中央': 'Club Atlético Rosario Central',
        '罗萨里奥中': 'Club Atlético Rosario Central',
        '塔勒瑞斯': 'Club Atlético Talleres',
        '拉普拉塔大学生': 'Club Estudiantes de La Plata',
        '拉普大学生': 'Club Estudiantes de La Plata',
        '圣菲联合': 'CA Unión Santa Fé',
        '圣塔菲联': 'CA Unión Santa Fé',
        '飓风': 'Club Atlético Huracán',
        '飓风队': 'Club Atlético Huracán',
        '老虎竞技': 'Club Atlético Tigre',
        '泰格雷': 'Club Atlético Tigre',
        '阿根廷青年人': 'Asociación Atlética Argentinos Juniors',
        '阿根青年人': 'Asociación Atlética Argentinos Juniors',
        '贝尔格拉诺': 'Club Atlético Belgrano',
        '班菲尔德': 'Club Atlético Banfield',
        '纽维尔老男孩': "Club Atlético Newell's Old Boys",
        '纽维尔老男': "Club Atlético Newell's Old Boys",
        '图库曼竞技': 'Club Atlético Tucumán',
        '拉普拉塔体操': 'Club de Gimnasia y Esgrima La Plata',
        '拉普体操': 'Club de Gimnasia y Esgrima La Plata',
        '圣马丁图库曼': 'Club Atlético San Martín (Tucumán)',
        '阿尔多西维': 'Club Atlético Aldosivi (MdP)',
        '圣胡安圣马丁': 'Club Atlético San Martín (SJ)',
        '圣胡安圣马': 'Club Atlético San Martín (SJ)',
        '帕特罗纳图': 'Club Atlético Patronato',
        '老虎大学': 'Tigres UANL',
        '蒙特雷': 'CF Monterrey',
        '墨西哥美洲': 'CF América',
        '蓝十字': 'CD Cruz Azul',
        '帕丘卡': 'CF Pachuca',
        '桑托斯拉古纳': 'Santos Laguna',
        '桑托斯拉古': 'Santos Laguna',
        '瓜达拉哈拉': 'Deportivo Guadalajara',
        '莱昂': 'Club León FC',
        '托卢卡': 'Deportivo Toluca',
        '美洲狮': 'UNAM Pumas',
        '普马斯': 'UNAM Pumas',
        '克雷塔罗': 'Querétaro FC',
        '蒂华纳': 'Club Tijuana',
        '拿加沙': 'Club Necaxa',
        '内卡萨': 'Club Necaxa',
        '阿特拉斯': 'Atlas Guadalajara',
        '莫雷利亚': 'Monarcas Morelia',
        '普埃布拉': 'Puebla FC',
        '普埃布拉大学': 'Lobos BUAP',
        '普埃布拉自': 'Lobos BUAP',
        '韦拉克鲁斯': 'Tiburones Rojos de Veracruz',
        '青岛中能': 'Qingdao Jonoon',
        '保定容大': 'Baoding Yingli Yitong',
        '巴蒂卡': 'Baltika Kaliningrad',
        '莫斯科斯巴达B队': 'Spartak 2 Moscow',
        '莫巴达B队': 'Spartak 2 Moscow',
        '莫斯巴B队': 'Spartak 2 Moscow',
        '索契': 'FC Sochi',
        '圣彼德堡泽尼特B队': 'Zenit 2 St. Petersburg',
        '泽尼特B队': 'Zenit 2 St. Petersburg',
        '坦波夫斯巴达': 'FK Tambov',
        '坦波夫': 'FK Tambov',
        '伏尔加格勒': 'Rotor Volgograd',
        '罗托伏尔加': 'Rotor Volgograd',
        '奥林彼特': 'FK Nizhny Novgorod',
        '下诺夫哥罗': 'FK Nizhny Novgorod',
        '阿华加德': 'Avangard Kursk',
        '库尔斯克前': 'Avangard Kursk',
        '克拉斯诺达尔B队': 'FK Krasnodar 2',
        '克拉斯B队': 'FK Krasnodar 2',
        '西伯尔': 'Sibir Novosibirsk',
        '卡希梅基': 'FK Khimki',
        '希姆基': 'FK Khimki',
        '莫斯科切尔塔诺沃': 'Chertanovo Moscow',
        '莫斯切尔塔': 'Chertanovo Moscow',
        '莫切尔塔诺': 'Chertanovo Moscow',
        '图们': 'FK Tyumen',
        'FC秋明': 'FK Tyumen',
        '阿尔马维尔': 'FK Armavir',
        '卢恩吉亚': 'Luch Vladivostok',
        '沃罗涅日火炬': 'Fakel Voronezh',
        '沃罗涅日火': 'Fakel Voronezh',
        '哈夫纳夫约杜尔': 'FH Hafnarfjördur',
        '哈夫纳夫约': 'FH Hafnarfjördur',
        '瓦路尔': 'Valur Reykjavík',
        '维京格': 'Víkingur Reykjavík',
        '维京古尔': 'Víkingur Reykjavík',
        'KR雷克雅未克': 'KR Reykjavík',
        'KR雷克雅': 'KR Reykjavík',
        '加尔扎拜尔星': 'UMF Stjarnan Gardabaer',
        '斯塔尔南': 'UMF Stjarnan Gardabaer',
        'KA阿克雷里': 'KA Akureyri',
        'KA阿克雷': 'KA Akureyri',
        '贝雷达比历克': 'Breidablik Kópavogur',
        '贝雷达比历': 'Breidablik Kópavogur',
        '弗约尼尔': 'Fjölnir Reykjavík',
        '韦斯特曼纳埃亚尔': 'ÍBV Vestmannaeyjar',
        'IBV韦斯': 'ÍBV Vestmannaeyjar',
        '格林达维克': 'UMF Grindavík',
        '费基尔': 'Fylkir Reykjavík',
        '凯夫拉维克': 'Keflavík ÍF',
        '百万富翁': 'Millonarios FC',
        '圣菲独立': 'Independiente Santa Fe',
        '巴兰基利亚青年': 'Junior FC',
        '麦德林国民竞技': 'Atlético Nacional',
        '麦德林独立': 'Independiente Medellín',
        '托利马体育': 'Deportes Tolima',
        '卡利体育会': 'Deportivo Cali',
        '意达古': 'Rionegro Águilas',
        '卡利阿美利加': 'CD América de Cali',
        '云斯卡尔达斯': 'Once Caldas',
        '柏斯度': 'Deportivo Pasto',
        '阿利安萨': 'Alianza Petrolera',
        '拉伊奎达德': 'CD La Equidad',
        '布卡拉曼格': 'Atlético Bucaramanga',
        '修罗': 'CD Atlético Huila',
        '帕特里奥坦斯': 'Boyacá Patriotas FC',
        '贾奎斯科尔多巴': 'Jaguares de Córdoba',
        '恩维加多': 'Envigado FC',
        '茨高': 'Boyacá Chicó FC',
        '利昂内斯': 'Leones FC',
        '大连实德': 'Dalian Yifang',
        '北京理工大学': 'Beijing BIT',
        '成都天诚': 'Chengdu Tiancheng',
        '叙利亚人': 'Syrianska FC',
        '奥特维达堡': 'Atvidabergs FF',
        '阿斯特沃尔加': 'Volgar Astrakhan',
        '沈阳中泽': 'Shenyang Zhongze',
        '安吉尔霍姆斯': 'Ängelholms FF',
        '圣彼得堡迪纳摩': 'Dinamo Bryansk',
        '永斯基': 'Ljungskile SK',
        '下卡姆斯克石油': 'Neftekhimik Nizhnekamsk',
        '广东日之泉': 'unknown',
        '罗森达尔': 'RBC Roosendaal',
        '洛卡诺': 'FC Locarno',
        '艾尔德里联': 'Airdrieonians FC',
        '贝林佐纳': 'AC Bellinzona',
        '考登比亚': 'Cowdenbeath FC',
        '比尔': 'FC Biel-Bienne',
        '米亚尔比': 'Mjällby AIF',
        '阿西里斯卡': 'Assyriska BK',
        '索科尔萨拉托夫': 'Sokol Saratov',
        '瑞狄恩巴克': 'Baikal Irkutsk',
        '尤特斯科腾': 'Utsiktens BK',
        '湖北华凯尔': 'unknown',
        '尼奈斯': 'FC Stade Nyonnais',
        '卡洛治': 'Etoile Carouge FC',
        '德勒蒙特': 'SR Delémont',
        '布鲁尔': 'SC Brühl SG',
        '艾比安斯特宁': 'Stirling Albion FC',
        '重庆FC': 'Chongqing F.C.',
        '胡斯华纳': 'Husqvarna FF',
        '卡马斯': 'KamAZ Naberezhnye Chelny',
        '呼和浩特': 'unknown',
        '马卡耶': 'Macaé Esporte Futebol Clube (RJ)',
        'ABC纳塔尔': 'unknown',
        '塞尔福斯': 'UMF Selfoss',
        '纳塔尔美洲': 'unknown',
        '卡西亚斯': 'S.E.R. Caxias do Sul (RS)',
        '沙古尔罗': 'SC Salgueiros',
        '伊帕廷加': 'Ipatinga Futebol Clube',
        '豪卡尔': 'Haukar Hafnarfjördur',
        '瓜达拉哈拉大学': 'CD Leones Negros de la UdeG',
        '亚美黎加纳SP': 'Guaratinguetá Futebol Ltda. (SP)',
        '托尔阿克雷里': 'Thór Akureyri',
        '弗拉姆': 'Fram Reykjavík',
        '雷克尼': 'Leiknir Reykjavík',
        '圣卡埃塔诺': 'AD São Caetano (SP)',
        '特科斯': 'Estudiantes Tecos',
        '特罗图尔': 'Thróttur Reykjavík',
        '奥拉夫斯维克维京': 'UMF Víkingur Ólafsvík',
        'IA阿克拉内斯': 'ÍA Akranes',
        '亚特兰特': 'CF Atlante',
        '阿莱皮拉卡': 'Agremiação Sportiva Arapiraquense (AL)',
        '圣路易斯': 'Atlético de San Luis',
        '库利亚坎': 'Dorados de Sinaloa',
        '伊卡萨': 'AD Recreativa Cultural Icasa (CE)',
        '美洲虎': 'Jaguares de Chiapas Premier',
        '巴鲁埃里': 'Grêmio Barueri Futebol Ltda.',
        '美国芝华士': 'CD Chivas USA',
        '莫日米林': 'Mogi Mirim Esporte Clube (SP)',
        '巴甘蒂诺': 'Clube Atlético Bragantino (SP)',
        '葡萄牙人': 'Associação Portuguesa de Desportos (SP)',
        '图佩': 'Tupi Football Club (MG)',
        '累西腓航海': 'Clube Náutico Capibaribe',
        '若因维利': 'Joinville EC (SC)',
        '卢维丹斯': 'Luverdense Esporte Clube (MT)',
        '阿姆施泰滕': 'SKU Amstetten',
        '伊韦尔顿': 'Yverdon-Sport FC',
        '沈阳东进': 'unknown',
        '布格勒斯特祖云斯': 'unknown',
        '圣克鲁斯': 'Santa Cruz Futebol Clube (PE)',
        'ACS蒂米索拉': 'ACS Poli Timisoara',
        '于默奥': 'Umeå FC',
        '捷尔任斯克化工者': 'Khimik Dzerzhinsk',
        '萨科林': 'Sakhalin Yuzhno-Sakhalinsk',
        '湖北绿茵': 'unknown',
        '南京有有': 'unknown',
        '上海浦东中邦': 'unknown',
        '纳茲兰': 'Angusht Nazran',
        '塞尤特恩纳吉亚': 'Salyut Belgorod',
        '库兹巴斯冶金': 'unknown',
        '拉蒙特LS': 'FC Le Mont LS',
        '沃伦': 'FC Wohlen',
        '拉茨流浪者': 'Raith Rovers FC',
        '布里金城': 'Brechin City FC',
        '泽姆楚芝纳': 'Zhemchuzhina Sochi',
        '阿帕多恩': 'AGOVV Apeldoorn',
        '邓巴顿': 'Dumbarton FC',
        '芬丹': 'SC Veendam',
        '布里安斯克迪纳摩': 'Dinamo Bryansk',
        '特温特青年队': 'FC Twente Enschede Youth',
        'FC诺夫哥罗德': 'Spartak Nizhniy Novgorod',
        '安徽九方': 'Anhui Jiufang FC',
        '弗拉基米尔鱼雷': 'Torpedo Vladimir',
        '阿喀琉斯': "Achilles '29",
        '新罗西斯克黑海人': "Spartak Nizhniy Novgorod",
        '甘马雷斯B队': "Vitória Guimarães SC B",
        '吉马良B队': "Vitória Guimarães SC B",
        '本菲卡B队': "SL Benfica B",
        '布拉加B队': "SC Braga B",
        '法伦斯': "SC Farense",
        '法马利康': "FC Famalicão",
        '波尔图B队': "FC Porto B",
        '科维良': "SC Covilhã",
        '奥利维伦斯': "UD Oliveirense",
        '奥利韦恩斯': "UD Oliveirense",
        '马弗拉': "CD Mafra",
        '马夫拉': "CD Mafra",
        '哥利亚': "unknown",
        '锡比乌托尼亚': "unknown",
        '科瓦彼达迪': "CD Cova Piedade",
        '雷克索斯': "Leixões SC",
        '维塞乌': "Académico Viseu FC",
        '瓦兹姆': "Varzim SC",
        '瓦尔津': "Varzim SC",
        '里斯本竞技B队': "Sporting CP B",
        '皇家体育队': "Real Sport Clube",
        '弗里姆德': "SC Freamunde",
        '法菲': "AD Fafe",
        '查卡里塔青年': "Club Atlético Chacarita Juniors",
        '奥林匹奥': "Olimpo de Bahía Blanca",
        '兵工厂': "Arsenal de Sarandí FC",
        '坦珀利': "Temperley",
        '维萨拉': "FC Vizela",
        '拉斐拉竞技': "Atlético de Rafaela",
        '塔古穆里斯': "ASA Tirgu Mures",
        '葡萄牙竞技': "Atlético CP",
        '萨米恩托': "Club Atlético Sarmiento (Junin)",
        '潘杜里': "Pandurii Targu Jiu",
        '里斯本东方': "Clube Oriental Lissabon",
        '基尔梅斯': "Quilmes Atlético Club",
        '普洛耶什蒂': "Petrolul Ploiesti",
        '古积大学': "Universitatea Cluj",
        '马里迪莫B队': "CS Marítimo B",
        '泰罗芬斯': "CD Trofense",
        '全男孩竞技': "CA All Boys Buenos Aires",
        '西罗尔尼姆特': "Ceahlaul Piatra Neamt",
        '纳瓦尔': "Naval 1º de Maio",
        '新芝加哥': "Nueva Chicago",
        '布加勒斯特快速': "Rapid Bucharest",
        '法迪马': "CD Fátima",
        '北克鲁塞罗': "Club Mutual Crucero del Norte",
        '布拉索夫': "FC Brasov",
        '加拉茨钢铁': "Otelul Galati",
        '瓦斯卢伊': "FC Vaslui",
        '科罗纳巴索夫': "Corona Brasov",
        '萨格亚塔': "Sageata Navodari",
        '塞维林堡': "unknown",
        '米奥文尼': "unknown",
        '斯朴图尔': "unknown",
    }

    def get(self, name):
        return self.team_chinese_2_english_dict[name]

