# 将500的中文队名转为transfermkt的英文名

class Chinese_2_english:
    def __init__(self):
        self.team_chinese_2_english_dict = {
        '曼彻斯特城' : 'Manchester City',
        '伯恩利' : 'Burnley FC',
        '伯恩茅斯' : 'AFC Bournemouth',
        '水晶宫' : 'Crystal Palace',
        '西布罗姆维奇' : 'West Bromwich Albion',
        '哈德斯菲尔德' : 'Huddersfield Town',
        '阿森纳' : 'Arsenal FC',
        '利物浦' : 'Liverpool FC',
        '布赖顿' : 'Brighton & Hove Albion',
        '曼彻斯特联' : 'Manchester United',
        '曼联' : 'Manchester United',
        '沃特福德' : 'Watford FC',
        '纽卡斯尔联' : 'Newcastle United',
        '切尔西' : 'Chelsea FC',
        '南安普敦' : 'Southampton FC',
        '斯旺西' : 'Swansea City',
        '斯托克城' : 'Stoke City',
        '托特纳姆热刺' : 'Tottenham Hotspur',
        '托特纳姆热' : 'Tottenham Hotspur',
        '莱切斯特城' : 'Leicester City',
        '西汉姆联' : 'West Ham United',
        '埃弗顿' : 'Everton FC',
        '狼队' : 'Wolverhampton Wanderers',
        '加的夫城' : 'Cardiff City',
        '富勒姆' : 'Fulham FC',
        '阿斯顿维拉' : 'Aston Villa',
        '米德尔斯堡' : 'Middlesbrough FC',
        '德比郡' : 'Derby County',
        '普雷斯顿' : 'Preston North End',
        '米尔沃尔' : 'Millwall FC',
        '布伦特福德' : 'Brentford FC',
        '谢菲尔德联' : 'Sheffield United',
        '布里斯托尔城' : 'Bristol City',
        '伊普斯维奇' : 'Ipswich Town',
        '利兹联' : 'Leeds United',
        '诺维奇' : 'Norwich City',
        '谢菲尔德星期三' : 'Sheffield Wednesday',
        '女王公园巡游者' : 'Queens Park Rangers',
        '诺丁汉森林' : 'Nottingham Forest',
        '赫尔城' : 'Hull City',
        '伯明翰' : 'Birmingham City',
        '雷丁' : 'Reading FC',
        '博尔顿' : 'Bolton Wanderers',
        '巴恩斯利' : 'Barnsley FC',
        '伯顿' : 'Burton Albion',
        '桑德兰' : 'Sunderland AFC',
        '维冈竞技' : 'Wigan Athletic',
        '布莱克本' : 'Blackburn Rovers',
        '什鲁斯伯里' : 'Shrewsbury Town',
        '罗瑟汉姆' : 'Rotherham United',
        '斯肯索普' : 'Scunthorpe United',
        '查尔顿' : 'Charlton Athletic',
        '普利茅斯' : 'Plymouth Argyle',
        '朴茨茅斯' : 'Portsmouth FC',
        '彼得堡联' : 'Peterborough United',
        '南安联' : 'Southend United',
        '布拉德福德' : 'Bradford City',
        '布莱克浦' : 'Blackpool FC',
        '布里斯托尔流浪' : 'Bristol Rovers',
        '福利特伍德' : 'Fleetwood Town',
        '唐卡斯特' : 'Doncaster Rovers',
        '牛津联' : 'Oxford United',
        '吉灵汉姆' : 'Gillingham FC',
        'AFC温布尔登' : 'AFC Wimbledon',
        '沃尔索尔' : 'Walsall FC',
        '罗奇代尔' : 'Rochdale AFC',
        '奥德汉姆' : 'Oldham Athletic',
        '北安普敦' : 'Northampton Town',
        '米尔顿凯恩斯' : 'Milton Keynes Dons',
        '贝里' : 'Bury FC',
        '阿克宁顿' : 'Accrington Stanley',
        '卢顿' : 'Luton Town',
        '韦康比流浪者' : 'Wycombe Wanderers',
        '埃克赛特城' : 'Exeter City',
        '诺茨郡' : 'Notts County',
        '考文垂' : 'Coventry City',
        '林肯城' : 'Lincoln City',
        '曼斯菲尔德' : 'Mansfield Town',
        '斯文登' : 'Swindon Town',
        '卡利斯尔联' : 'Carlisle United',
        '纽波特郡' : 'Newport County',
        '剑桥联' : 'Cambridge United',
        '科尔切斯特联' : 'Colchester United',
        '克劳利' : 'Crawley Town',
        '克鲁' : 'Crewe Alexandra',
        '斯蒂文尼奇' : 'Stevenage FC',
        '切尔滕汉姆' : 'Cheltenham Town',
        '格林斯比' : 'Grimsby Town',
        '约维尔' : 'Yeovil Town',
        '维尔港' : 'Port Vale FC',
        '格兰森林流浪' : 'Forest Green Rovers',
        '莫克姆' : 'Morecambe FC',
        '巴尼特' : 'Barnet FC',
        '切斯特菲尔德' : 'Chesterfield FC',
        '麦克尔斯菲尔德' : 'Macclesfield Town',
        '赫雷福德联' : 'FC Hereford',
        '奥尔德肖特' : 'Aldershot Town',
        '莱顿东方' : 'Leyton Orient',
        '特兰米尔' : 'Tranmere Rovers',
        '哈特利普' : 'Hartlepool United',
        '达根汉姆' : 'Dagenham & Redbridge FC',
        '约克城' : 'York City',
        '托基联' : 'Torquay United FC',
        '斯托克港' : 'Stockport County',
        '巴塞罗那' : 'FC Barcelona',
        '马德里竞技' : 'Atlético Madrid',
        '皇家贝蒂斯' : 'Real Betis Balompié',
        '皇家马德里' : 'Real Madrid',
        '皇马' : 'Real Madrid',
        '巴伦西亚' : 'Valencia CF',
        '赫塔费' : 'Getafe CF',
        '埃瓦尔' : 'SD Eibar',
        '塞维利亚' : 'Sevilla FC',
        '西班牙人' : 'RCD Espanyol Barcelona',
        '阿拉维斯' : 'Deportivo Alavés',
        '维戈塞尔塔' : 'Celta de Vigo',
        '莱加内斯' : 'CD Leganés',
        '毕尔巴鄂竞技' : 'Athletic Bilbao',
        '莱万特' : 'Levante UD',
        '皇家社会' : 'Real Sociedad',
        '比利亚雷亚尔' : 'Villarreal CF',
        '赫罗纳' : 'Girona FC',
        '拉科鲁尼亚' : 'Deportivo de La Coruña',
        '拉斯帕尔马斯' : 'UD Las Palmas',
        '马拉加' : 'Málaga CF',
        '巴列卡诺' : 'Rayo Vallecano',
        '韦斯卡' : 'SD Huesca',
        '希洪竞技' : 'Sporting Gijón',
        '萨拉戈萨' : 'Real Zaragoza',
        '巴利亚多利德' : 'Real Valladolid CF',
        '努曼西亚' : 'CD Numancia',
        '皇家奥维耶多' : 'Real Oviedo',
        '加的斯' : 'Cádiz CF',
        '奥萨苏纳' : 'CA Osasuna',
        '格拉纳达CF' : 'Granada CF',
        '特内里费' : 'CD Tenerife',
        '鲁勾' : 'CD Lugo',
        '阿尔科尔孔' : 'AD Alcorcón',
        '塔拉戈纳' : 'Gimnàstic de Tarragona',
        '雷乌斯' : 'CF Reus Deportiu',
        '科尔多瓦' : 'Córdoba CF',
        '阿尔瓦塞特' : 'Albacete Balompié',
        '阿尔梅里亚' : 'UD Almería',
        '莱昂内萨' : 'Cultural Leonesa',
        '巴塞罗那B队' : 'FC Barcelona B',
        '合亚' : 'Lorca FC',
        '塞维利亚B队' : 'Sevilla Atlético',
        '埃尔切' : 'Elche CF',
        '瑞欧马加达宏达' : 'CF Rayo Majadahonda',
        '马洛卡' : 'RCD Mallorca',
        '穆尔西亚天主大学' : 'UCAM Murcia CF',
        '米兰德斯' : 'CD Mirandés',
        '桑坦德竞技' : 'Racing Santander',
        '毕尔巴鄂B队' : 'Bilbao Athletic',
        '埃尔库莱斯' : 'Hércules CF',
        '邦费雷迪纳' : 'SD Ponferradina',
        '利亚格斯特拉' : 'UE Llagostera',
        '韦尔瓦' : 'Recreativo Huelva',
        '萨瓦德尔' : 'CE Sabadell',
        '穆尔西亚' : 'UCAM Murcia CF',
        '皇家马德里B队' : 'Real Madrid Castilla',
        '皇家哈恩' : 'Real Jaén CF',
        'CD瓜达拉哈拉' : 'CD Guadalajara',
        '萨雷斯' : 'Xerez Deportivo FC',
        '卡塔赫纳' : 'FC Cartagena',
        '维拉利尔B队' : 'Villarreal CF B',
        '阿尔科亚诺' : 'CD Alcoyano',
        '萨拉曼卡' : 'Salamanca CF UDS',
        '巴黎圣日尔曼' : 'Paris Saint-Germain',
        '摩纳哥' : 'AS Monaco',
        '里昂' : 'Olympique Lyon',
        '马赛' : 'Olympique Marseille',
        '雷恩' : 'Stade Rennais FC',
        '波尔多' : 'FC Girondins Bordeaux',
        '圣埃蒂安' : 'AS Saint-Étienne',
        '尼斯' : 'OGC Nice',
        '南特' : 'FC Nantes',
        '蒙彼利埃' : 'HSC Montpellier',
        '第戎' : 'FCO Dijon',
        '甘冈' : 'EA Guingamp',
        '亚眠' : 'SC Amiens',
        '昂热' : 'SCO Angers',
        '斯特拉斯堡' : 'RC Strasbourg Alsace',
        '卡昂' : 'SM Caen',
        '里尔' : 'LOSC Lille',
        '图卢兹' : 'FC Toulouse',
        '特鲁瓦' : 'ES Troyes AC',
        '梅斯' : 'FC Metz',
        '兰斯' : 'Stade Reims',
        '尼姆' : 'Nîmes Olympique',
        '瓦朗谢纳' : 'Valenciennes FC',
        '贝兹尔' : 'AS Béziers',
        '贝济耶' : 'AS Béziers',
        '朗斯' : 'RC Lens',
        '尼奥尔' : 'FC Chamois Niort',
        '尼奥特' : 'FC Chamois Niort',
        '格勒诺布尔' : 'Grenoble Foot 38',
        '阿雅克肖GFCO' : 'GFC Ajaccio',
        'GFC阿雅' : 'GFC Ajaccio',
        '巴黎FC' : 'Paris FC',
        '克莱蒙' : 'Clermont Foot Auvergne 63',
        '克莱蒙特' : 'Clermont Foot Auvergne 63',
        '洛里昂' : 'FC Lorient',
        '勒阿弗尔' : 'AC Le Havre',
        '沙托鲁' : 'LB Châteauroux',
        '圣旺红星' : 'Red Star FC',
        '索肖' : 'FC Sochaux-Montbéliard',
        '布雷斯特' : 'Stade Brest 29',
        '阿雅克肖' : 'AC Ajaccio',
        '欧塞尔' : 'AJ Auxerre',
        '南锡' : 'AS Nancy-Lorraine',
        '奥尔良' : 'US Orléans',
        '布尔格' : 'Bourg-en-Bresse Péronnas 01',
        '奎维利鲁昂' : 'US Quevilly',
        '图尔' : 'Tours FC',
        '巴斯蒂亚' : 'SC Bastia',
        '伊维恩' : 'FC Évian Thonon Gaillard',
        '拉瓦勒' : 'Stade Laval',
        '克雷泰伊' : 'US Créteil-Lusitanos',
        '阿尔勒' : 'Athlétic Club Arlésien',
        '伊斯特尔' : 'Istres Football Club',
        'CA巴斯蒂亚' : 'CA Bastia',
        '色当' : 'CS Sedan-Ardennes',
        '勒芒' : 'FC Le Mans',
        '布洛涅' : 'US Boulogne',
        '瓦讷' : 'OC Vannes',
        '拜仁慕尼黑' : 'Bayern Munich',
        '沙尔克04' : 'FC Schalke 04',
        '霍芬海姆' : 'TSG 1899 Hoffenheim',
        '多特蒙德' : 'Borussia Dortmund',
        '勒沃库森' : 'Bayer 04 Leverkusen',
        '莱比锡红牛' : 'RB Leipzig',
        '斯图加特' : 'VfB Stuttgart',
        '法兰克福' : 'Eintracht Frankfurt',
        '门兴格拉德巴赫' : 'Borussia Mönchengladbach',
        '柏林赫塔' : 'Hertha BSC',
        '云达不来梅' : 'SV Werder Bremen',
        '奥格斯堡' : 'FC Augsburg',
        '汉诺威96' : 'Hannover 96',
        '美因茨' : '1.FSV Mainz 05',
        '弗赖堡' : 'SC Freiburg',
        '沃尔夫斯堡' : 'VfL Wolfsburg',
        '汉堡' : 'Hamburger SV',
        '科隆' : '1. FC Köln',
        '杜塞尔多夫' : 'Fortuna Düsseldorf',
        '纽伦堡' : '1.FC Nuremberg',
        '基尔高士丁' : 'Holstein Kiel',
        '比勒费尔德' : 'Arminia Bielefeld',
        '雷根斯堡' : 'SSV Jahn Regensburg',
        '波鸿' : 'VfL Bochum',
        '杜伊斯堡' : 'MSV Duisburg',
        '柏林联合' : '1.FC Union Berlin',
        '因戈尔施塔特' : 'FC Ingolstadt 04',
        '达姆施塔特' : 'SV Darmstadt 98',
        '桑德豪森' : 'SV Sandhausen',
        '圣保利' : 'FC St. Pauli',
        '海登海姆' : '1.FC Heidenheim 1846',
        '德累斯顿' : 'SG Dynamo Dresden',
        '菲尔特' : 'SpVgg Greuther Fürth',
        '奥厄' : 'FC Erzgebirge Aue',
        '不伦瑞克' : 'Eintracht Braunschweig',
        '凯泽斯劳滕' : '1.FC Kaiserslautern',
        '帕德博恩' : 'SC Paderborn 07',
        '马迪堡' : '1.FC Magdeburg',
        '卡尔斯鲁厄' : 'Karlsruher SC',
        '慕尼黑1860' : 'TSV 1860 Munich',
        '维尔茨堡踢球者' : 'Würzburger Kickers',
        'FSV法兰克福' : 'FSV Frankfurt',
        '亚伦' : 'VfR Aalen',
        '科特布斯' : 'FC Energie Cottbus',
        '罗斯托克' : 'FC Hansa Rostock',
        '亚琛' : 'Alemannia Aachen',
        '奥伯豪森' : 'Rot-Weiß Oberhausen',
        '奥斯纳布吕克' : 'VfL Osnabrück',
        '尤文图斯' : 'Juventus FC',
        '那不勒斯' : 'SSC Napoli',
        '罗马' : 'AS Roma',
        '国际米兰' : 'Inter Milan',
        '拉齐奥' : 'SS Lazio',
        'AC米兰' : 'AC Milan',
        '亚特兰大' : 'Atalanta BC',
        '佛罗伦萨' : 'ACF Fiorentina',
        '都灵' : 'Torino FC',
        '桑普多利亚' : 'UC Sampdoria',
        '萨索洛' : 'US Sassuolo',
        '热那亚' : 'Genoa CFC',
        '乌迪内斯' : 'Udinese Calcio',
        '切沃' : 'Chievo Verona',
        '博洛尼亚' : 'Bologna FC 1909',
        '卡利亚里' : 'Cagliari Calcio',
        '费拉拉SPAL' : 'SPAL 2013',
        '克罗托内' : 'FC Crotone',
        '维罗纳' : 'Hellas Verona',
        '贝内文托' : 'Benevento Calcio',
        '恩波利' : 'FC Empoli',
        '帕尔马' : 'Parma Calcio 1913',
        '弗洛西诺内' : 'Frosinone Calcio',
        '巴勒莫' : 'US Palermo',
        '威尼斯' : 'Venezia FC',
        '巴里' : 'FC Bari 1908',
        '希塔德拉' : 'AS Cittadella',
        '佩鲁贾' : 'AC Perugia Calcio',
        '霍治亚' : 'Foggia Calcio',
        '斯佩齐亚' : 'Spezia Calcio',
        '卡尔皮' : 'Carpi FC 1909',
        '萨勒尼塔纳' : 'US Salernitana 1919',
        '切塞纳' : 'Romagna Centro Cesena FC',
        '科雷蒙尼斯' : 'US Cremonese',
        '阿韦利诺' : 'AS Livorno',
        '布雷西亚' : 'Brescia Calcio',
        '佩斯卡拉' : 'Delfino Pescara 1936',
        '阿斯科利' : 'Ascoli Calcio',
        '诺瓦拉' : 'Novara Calcio 1908',
        '恩特拉' : 'Virtus Entella',
        '韦尔切利' : 'FC Pro Vercelli 1892',
        '特拉纳' : 'Ternana Calcio',
        '莱切' : 'US Lecce',
        '帕多瓦' : 'Calcio Padova',
        '比萨' : 'AC Pisa 1909',
        '拉蒂那' : 'Latina Calcio 1932',
        '维琴察' : 'LR Vicenza 1902',
        '特腊帕尼' : 'Trapani Calcio',
        '利沃诺' : 'AS Livorno',
        '兰恰诺' : 'SS Virtus Lanciano',
        '摩德纳' : 'Modena FC 2018',
        '科莫' : 'Como 1907',
        '卡塔尼亚' : 'Calcio Catania',
        '瓦雷泽' : 'Varese Calcio',
        '尤文斯塔比亚' : 'SS Juve Stabia',
        '锡耶纳' : 'Robur Siena',
        '雷吉纳' : 'Urbs Reggina 1914',
        '格罗瑟托' : 'US Grosseto 1912',
        '古比奥' : 'AS Gubbio 1910',
        '诺瑟里纳' : 'ASD Nocerina 1910',
        '阿尔比诺勒菲' : 'UC AlbinoLeffe',
        '皮亚琴察' : 'Piacenza Calcio 1919',
        '特里埃斯蒂纳' : 'US Triestina',
        '波图格鲁阿罗' : 'Portogruaro Calcio ASD',
        '波尔图' : 'FC Porto',
        '本菲卡' : 'SL Benfica',
        '里斯本竞技' : 'Sporting CP',
        '布拉加' : 'SC Braga',
        '里奥阿维' : 'Rio Ave FC',
        '查维斯' : 'GD Chaves',
        '马里迪莫' : 'CS Marítimo',
        '博阿维斯塔' : 'Boavista Porto FC',
        '吉马良斯' : 'Vitória Guimarães SC',
        '波尔蒂芒尼斯' : 'Portimonense SC',
        '通德拉' : 'CD Tondela',
        '比兰尼塞斯' : 'CF Belenenses',
        '艾维斯' : 'Desportivo Aves',
        '摩雷伦斯' : 'Moreirense FC',
        '塞图巴尔' : 'Vitória Setúbal FC',
        '菲伦斯' : 'CD Feirense',
        '费雷拉' : 'FC Paços de Ferreira',
        '埃斯托里尔' : 'GD Estoril Praia',
        '葡萄牙国民' : 'CD Nacional',
        '圣克拉拉' : 'CD Santa Clara',
        '阿罗卡' : 'FC Arouca',
        '科英布拉大学' : 'Académica Coimbra',
        '马德拉' : 'CF União Madeira',
        '佩纳菲尔' : 'FC Penafiel',
        '维森特' : 'Gil Vicente FC',
        '欧汉尼斯' : 'SC Olhanense',
        '贝拉马尔' : 'SC Beira-Mar',
        '圣彼得堡泽尼特' : 'Zenit St. Petersburg',
        '喀山红宝石' : 'Rubin Kazan',
        '安郅马哈奇卡拉' : 'Anzhi Makhachkala',
        '罗斯托夫' : 'FK Rostov',
        '莫斯科斯巴达' : 'Spartak Moscow',
        '苏维埃之翼' : 'Krylya Sovetov Samara',
        '莫斯科迪纳摩' : 'Dinamo Moscow',
        '莫斯科火车头' : 'Lokomotiv Moscow',
        '莫斯科中央陆军' : 'CSKA Moscow',
        '乌法' : 'FK Ufa',
        '图拉' : 'Arsenal Tula',
        '克拉斯诺达尔' : 'FK Krasnodar',
        '乌拉尔' : 'Ural Yekaterinburg',
        '格罗兹尼捷列克' : 'Akhmat Grozny',
        '奥伦堡加索维克' : 'FK Orenburg',
        '叶尼塞' : 'Enisey Krasnoyarsk',
        '辛历克' : 'Shinnik Yaroslavl',
        '托姆斯克' : 'Chertanovo Moscow',
        '阿姆卡尔' : 'Amkar Perm',
        '图斯诺' : 'FK Tosno',
        'SKA恩纳吉亚' : 'SKA Khabarovsk',
        '萨兰斯克' : 'Mordovia Saransk',
        '加拉塔萨雷' : 'Galatasaray SK',
        '费内巴切' : 'Fenerbahce SK',
        '伊斯坦布尔' : 'Basaksehir',
        '贝西克塔斯' : 'Besiktas JK',
        '特拉布宗体育' : 'Trabzonspor',
        '哥兹塔比' : 'Göztepe',
        '锡瓦斯体育' : 'Sivasspor',
        '卡斯帕萨' : 'Kasimpasa',
        '开塞利体育' : 'Kayserispor',
        '马拉耶士邦' : 'Yeni Malatyaspor',
        '阿卡沙' : 'Akhisarspor',
        '阿兰亚斯堡' : 'Alanyaspor',
        '布尔萨体育' : 'Bursaspor',
        '安塔利亚体育' : 'Antalyaspor',
        '科尼亚体育' : 'Konyaspor',
        '奥斯曼体育' : 'Osmanlispor FK',
        '根克勒比利吉' : 'Genclerbirligi Ankara',
        '卡拉比克体育' : 'Kardemir Karabükspor',
        '里泽斯堡' : 'Caykur Rizespor',
        '安卡拉古库' : 'MKE Ankaragücü',
        '波卢斯堡' : 'Boluspor',
        '尤姆尼耶士邦' : 'Ümraniyespor',
        '巴里科斯士邦' : 'Balikesirspor',
        '加济安泰普体育' : 'Gaziantepspor',
        '艾丹亚斯普' : 'Adanaspor',
        '梅尔辛' : 'Mersin Idmanyurdu',
        '加辛塔BB' : 'Gazisehir Gaziantep Futbol Kulübü',
        '库班' : 'Kuban Krasnodar',
        '莫斯科鱼雷' : 'Torpedo Moscow',
        '伏尔加诺夫哥罗德' : 'Volga Nizhniy Novgorod',
        '阿拉尼亚' : 'Spartak Vladikavkaz',
        '奈兹克斯巴达' : 'Spartak Nalchik',
        '埃斯基谢希尔体育' : 'Eskisehirspor',
        '阿辛耶斯堡' : 'Kayseri Erciyesspor',
        '伊拉兹斯堡' : 'Elazigspor',
        '奥尔杜体育' : 'Orduspor',
        '布卡体育' : 'Bucaspor',
        'PSV埃因霍温' : 'PSV Eindhoven',
        '阿贾克斯' : 'Ajax Amsterdam',
        '阿尔克马尔' : 'AZ Alkmaar',
        '费耶诺德' : 'Feyenoord Rotterdam',
        '乌德勒支' : 'FC Utrecht',
        '维迪斯' : 'Vitesse Arnhem',
        '海牙' : 'ADO Den Haag',
        '海伦芬' : 'SC Heerenveen',
        '兹沃勒' : 'PEC Zwolle',
        '赫拉克勒斯' : 'Heracles Almelo',
        'SBV精英' : 'Excelsior Rotterdam',
        '格罗宁根' : 'FC Groningen',
        '威廉二世' : 'Willem II Tilburg',
        '布雷达' : 'NAC Breda',
        '芬洛' : 'VVV-Venlo',
        '罗达JC' : 'Roda JC Kerkrade',
        '鹿特丹斯巴达' : 'Sparta Rotterdam',
        '特温特' : 'FC Twente Enschede',
        '阿贾克斯青年队' : 'Ajax Amsterdam',
        '福图纳锡塔德' : 'Fortuna Sittard',
        '奈梅亨' : 'NEC Nijmegen',
        '格拉夫夏普' : 'De Graafschap Doetinchem',
        '埃因霍温青年队' : 'PSV Eindhoven U21',
        '特尔斯达' : 'SC Telstar',
        '埃门' : 'FC Emmen',
        '坎布尔' : 'SC Cambuur-Leeuwarden',
        '阿尔梅勒城' : 'Almere City FC',
        '马斯特里赫特' : 'MVV Maastricht',
        '登博思' : 'FC Den Bosch',
        '埃因霍温FC' : 'FC Eindhoven',
        '多德勒支' : 'FC Dordrecht',
        '福伦丹' : 'FC Volendam',
        '奥斯' : 'TOP Oss',
        '阿克马尔青年队' : 'AZ Alkmaar U21',
        '前进之鹰' : 'Go Ahead Eagles Deventer',
        '瓦尔韦克' : 'RKC Waalwijk',
        '海尔蒙特' : 'Helmond Sport',
        '乌德勒支青年队' : 'FC Utrecht U21',
        '亨克' : 'KRC Genk',
        '布鲁日' : 'Club Brugge KV',
        '安德莱赫特' : 'RSC Anderlecht',
        '标准列日' : 'Standard Liège',
        '奥斯坦德' : 'KV Oostende',
        '安特卫普' : 'Royal Antwerp FC',
        '聚尔特瓦雷赫姆' : 'SV Zulte Waregem',
        '贝弗伦' : 'Waasland-Beveren',
        '圣图尔登' : 'Sint-Truidense VV',
        '色格拉布鲁日' : 'Cercle Brugge',
        '根特' : 'KAA Gent',
        '匹卢维兹' : 'Royal Excel Mouscron',
        '沙勒罗瓦' : 'RSC Charleroi',
        '欧本' : 'KAS Eupen',
        '科特赖克' : 'KV Kortrijk',
        '洛克伦' : 'KSC Lokeren',
        '洛默尔' : 'Lommel SK',
        '梅赫伦' : 'KV Mechelen',
        '韦斯特鲁' : 'KVC Westerlo',
        '鲁瑟拉勒' : 'KSV Roeselare',
        '圣吉罗斯' : 'Royale Union Saint Gilloise',
        '蒂比兹' : 'AFC Tubize',
        '奥德赫维里' : 'Oud-Heverlee Leuven',
        '维吉克' : 'KFCO Beerschot Wilrijk',
        '布隆德比' : 'Bröndby IF',
        '哥本哈根' : 'FC Copenhagen',
        '文德斯尔' : 'Vendsyssel FF',
        '奥尔堡' : 'Aalborg BK',
        '北西兰' : 'FC Nordsjaelland',
        '瓦埃勒' : 'Vejle Boldklub',
        '中日德兰' : 'FC Midtjylland',
        '桑德捷斯基' : 'SönderjyskE',
        '霍森斯' : 'AC Horsens',
        '兰纳斯' : 'Randers FC',
        '奥胡斯' : 'Aarhus GF',
        '欧登塞' : 'Odense Boldklub',
        '埃斯比约' : 'Esbjerg fB',
        '霍布罗' : 'Hobro IK',
        'HB科治' : 'HB Köge',
        '比利希尔星格' : 'FC Helsingör',
        '纳斯特维德' : 'Naestved Boldklub',
        '哈维德夫' : 'Hvidovre IF',
        '利恩比' : 'Lyngby BK',
        '维堡' : 'Viborg FF',
        '施克堡' : 'Silkeborg IF',
        '萨姆松体育' : 'Samsunspor',
        '马尼萨体育' : 'Manisaspor',
        '罗兰法斯特' : 'Nyköbing FC',
        '提斯特德' : 'Thisted FC',
        '腓特烈西亚' : 'FC Fredericia',
        '阿马盖尔' : 'BK Fremad Amager',
        '罗斯基德' : 'FC Roskilde',
        '利尔斯' : 'KSK Lierse Kempenzonen',
        '蒙斯' : 'RAEC Mons',
        '比尔肖特' : 'Beerschot AC',
        '西希兰' : 'FC Vestsjaelland',
    }

    def get(self, name):
        return self.team_chinese_2_english_dict[name]

